= Managing

Now that you have set up the Gateway you must configure the SS7 Stack and the Gateway. &THIS.PLATFORM;&THIS.APPLICATION;comes with a convenient user-friendly Graphical User Interface (GUI) and a Command Line Interface (CLI) that will allow you to configure, monitor and manage the Gateway.
While the CLI tool allows complete configuration and control of the Gateway, the GUI-based management enhances the usability of the Gateway and gives you the ability to configure and manage the SMSC Gateway dynamically.
This chapter will explain how to manage the Gateway effectively using both the GUI and the CLI.
 

.Configuring the SS7 Stack
You must configure the SS7 stack prior to configuring SMSC.
For details on configuring the SS7 Stack please refer to the RestComm SS7 Stack User Guide.
The RestComm SS7 Stack User Guide lists all available Shell commands and GUI operations to configure SS7.
In addition, help files are also available for every Shell command providing all details relevant to the command. 

.Configuring the Gateway
Please find below relevant information on configuring the Gateway

:leveloffset: +1

include::Section-Managing-Server-Settings.adoc[]

:leveloffset: -1

:leveloffset: +1

include::Section-Managing-SMPP-Server-Settings.adoc[]

:leveloffset: -1

:leveloffset: +1

include::Section-Managing-ESME-Settings.adoc[]

:leveloffset: -1

:leveloffset: +1

include::Section-Managing-SIP-Settings.adoc[]

:leveloffset: -1

:leveloffset: +1

include::Section-Managing-MAP-Version-Cache-Settings.adoc[]

:leveloffset: -1

:leveloffset: +1

include::Section-Managing-DB-Routing-Settings.adoc[]

:leveloffset: -1

:leveloffset: +1

include::Section-Managing-mproc-rules.adoc[]

:leveloffset: -1

:leveloffset: +1

include::Section-Managing-Stats.adoc[]

:leveloffset: -1
