
[[_mproc_rule_settings]]
= Message processing rules (mproc rules)

The fundamentals of mproc rules you can in the chapter <<_mproc_rules_fundamentals>>.
Here we will describe how to manage mproc rules. 

[[_mproc_rule_settings_create]]
== Create a mproc rule.

[[_mproc_rule_settings_create_cli]]
=== Using CLI

You can configure a new mproc rule by issuing the command smsc mproc add with appropriate parameters as described below. 

----

Name
	smsc mproc add

SYNOPSIS
	- General case (for customized mproc rules):
	smsc mproc add <class name> <id> <parameters list>

	- Default mproc rules implementation (<class name> is "mproc"):
	smsc mproc add mproc <id> networkidmask <networkId value> originnetworkidmask <networkId
	value> receiptnetworkidmask <networkId value> desttonmask <destination type of number>
	destnpimask <destination numbering plan	indicator>
	destdigmask <regular expression - destination number digits mask> sourcetonmask
	<source type of number> sourcenpimask <source numbering plan indicator>
	sourcedigmask <regular expression - source number digits mask>
	imsidigitsmask <regular expression - imsi digits mask> nnndigitsmask <regular expression
	- NetworkNodeNumber digits mask> originatingmask <SS7_MO | SS7_HR | SMPP | SIP | HTTP |
	-1> origesmenamemask <regualar expression - origination ESME name mask>
	originatorsccpaddressmask <originator SCCP CallingPartyAddress mask> processingtype
	<delivery processing type: SS7_SRI | SS7_MT | SMPP | SIP | -1> errorcode <internal SMSC
	GW delivery error code value> tlv_<tlv tag key>_<tlv value type> <tlv value> percent
	<percent value> newnetworkid <new networkId value> newdestton <new destination type of number>
	newdestnpi <new destination numbering plan indicator>
	adddestdigprefix <prefix value> addsourcedigprefix <prefix value>
	newsourceton <new source type of number> newsourcenpi
	<new source numbering plan indicator> newsourceaddr <new source address value> mtlocalsccpgt 
	<new gt of a local sccp address of an mt message> mtremotesccptt 
	<new tt for remote sccp address for mt message> hrbypass <false | true> dropaftersri 
	<false | true> newnetworkidaftersri <networkId value> dropaftertempfail <false | true> 
	newnetworkidaftertempfail <networkId value> droponarrival <false | true> rejectonarrival 
	<NONE | DEFAULT | UNEXPECTED_DATA_VALUE | SYSTEM_FAILURE |	THROTTLING | FACILITY_NOT_SUPPORTED>
	remove_tlv <tlv tag key>

DESCRIPTION

	This command is used to add a new mproc rule.

PARAMETERS

	Standard Parameters.
	class name - the name of class of mproc rules implementation. For the
	  default implementation (that is described here) class name is "mproc".
	id - a mandatory parameter that means a unique mproc identifier.

	networkidmask - an optional parameter.
	originnetworkidmask - an optional parameter.
	receiptnetworkidmask - an optional parameter.
	desttonmask - an optional parameter.
	destnpimask - an optional parameter.
	destdigmask - an optional parameter.
	sourcetonmask - an optional parameter.
	sourcenpimask - an optional parameter.
	sourcedigmask - an optional parameter.
	imsidigitsmask - an optional parameter.
	nnndigitsmask - an optional parameter.
	originatingmask - an optional parameter.
	origesmenamemask - an optional parameter.
	originatorsccpaddressmask - an optional parameter.
	processingtype - an optional parameter.
	errorcode - an optional parameter.
	tlv_<valuetype>_<tagkey> - an optional parameter.
	percent <percent value> - an optional parameter.

	newnetworkid - an optional parameter.
	newdestton - an optional parameter.
	newdestnpi - an optional parameter.
	adddestdigprefix - an optional parameter.
	addsourcedigprefix - an optional parameter.
	newsourceton - an optional parameter.
	newsourcenpi - an optional parameter.
	newsourceaddr - an optional parameter.
	mtlocalsccpgt - an optional parameter.
	mtremotesccptt - an optional parameter.
	makecopy - an optional parameter.
	hrbypass - an optional parameter.
	dropaftersri - an optional parameter.
	newnetworkidaftersri - an optional parameter.
	newnetworkidafterpermfail - an optional parameter.
	dropaftertempfail - an optional parameter.
	newnetworkidaftertempfail - an optional parameter.
	droponarrival - an optional parameter.
	rejectonarrival - an optional parameter.
	remove_tlv - an optional parameter.

EXAMPLES
	smsc mproc add mproc 1 networkidmask 11 newnetworkid 12
	smsc mproc add mproc 1 tlv_int_1550 13 newnetworkid 13
----
	
Description of parameters is in the chapter <<_mproc_rules_default>>.

[[_mproc_rule_settings_create_gui]]
=== Using GUI


. In the GUI Management Console for SMSC Gateway, click on 'Message Processing Rules' in the left panel. 
. The main panel will display the existing mproc rule (if any), one each in a row with corresponding actions (delete, update) for each row.
  Below this you will find buttons  'Create Default Message Processing Rule' and 'Create Custom Message Processing Rule'. If you have not implemented your own customized rule, the only option for you is 'Create Default Message Processing Rule'. The 'Create Message Processing Rule' window will display all proc rule parameters that must be defined by you.
  For more details of these parameters please refer to the descriptions of the CLI commands for the same in the preceding section. 
. If you have implemented your own customized rules than you can use the button 'Create Custom Message Processing Rule'. For a custom mproc rule you need to configure rule Id, Class Name and Parameters (as a plain string that will be parsed by your customized rules). 
. Enter appropriate values for all the parameters and then click on the 'Create' button at the bottom of this 'Create Message Processing Rule' window.
  This action will create a new mproc rule with parameters as defined by you. 
. If there is an error in defining the mproc rule, then you will find the details of the error in the Management Console Log section below. 

[[_mproc_rule_settings_modify]]
== Modify a mproc rule.

[[_mproc_rule_settings_modify_cli]]
=== Using CLI

You can modify an existent mproc rule by issuing the command smsc mproc modify with appropriate parameters as described below. 

----

Name
	smsc mproc modify

SYNOPSIS
	- General case (for customized mproc rules):
	smsc mproc modify <id> <parameters list>

	- Default mproc rules implementation:
	smsc mproc modify <id> networkidmask <networkId value> originnetworkidmask <networkId
	value> receiptnetworkidmask <networkId value> desttonmask <destination type of number>
	destnpimask <destination numbering plan	indicator>
	destdigmask <regular expression - destination number digits mask> sourcetonmask
	<source type of number> sourcenpimask <source numbering plan indicator>
	sourcedigmask <regular expression - source number digits mask>
	imsidigitsmask <regular expression - imsi digits mask> nnndigitsmask <regular expression
	- NetworkNodeNumber digits mask> originatingmask <SS7_MO | SS7_HR | SMPP | SIP | HTTP |
	-1> origesmenamemask <regualar expression - origination ESME name mask>
	originatorsccpaddressmask <originator SCCP CallingPartyAddress mask> processingtype
	<delivery processing type: SS7_SRI | SS7_MT | SMPP | SIP | -1> errorcode <internal SMSC
	GW delivery error code value> tlv_<tlv tag key>_<tlv value type> <tlv value> percent
	<percent value> newnetworkid <new networkId value> newdestton <new destination type of number>
	newdestnpi <new destination numbering plan indicator>
	adddestdigprefix <prefix value> addsourcedigprefix <prefix value>
	newsourceton <new source type of number> newsourcenpi
	<new source numbering plan indicator> newsourceaddr <new source address value> 
	mtlocalsccpgt <new gt of a local sccp address of an mt message> mtremotesccptt 
	<new tt for remote sccp address for mt message> hrbypass <false | true> dropaftersri 
	<false | true> newnetworkidaftersri <networkId value> dropaftertempfail <false | true> 
	newnetworkidaftertempfail <networkId value> droponarrival <false | true> rejectonarrival 
	<NONE | DEFAULT | UNEXPECTED_DATA_VALUE | SYSTEM_FAILURE | THROTTLING | FACILITY_NOT_SUPPORTED> 
	remove_tlv <tlv tag key>

DESCRIPTION

	This command is used to modify an existent mproc rule.

PARAMETERS

	Standard Parameters.
	id - a mandatory parameter that means a unique mproc identifier.

	networkidmask - an optional parameter.
	originnetworkidmask - an optional parameter.
	receiptnetworkidmask - an optional parameter.
	desttonmask - an optional parameter.
	destnpimask - an optional parameter.
	destdigmask - an optional parameter.
	sourcetonmask - an optional parameter.
	sourcenpimask - an optional parameter.
	sourcedigmask - an optional parameter.
	imsidigitsmask - an optional parameter.
	nnndigitsmask - an optional parameter.
	originatingmask - an optional parameter.
	origesmenamemask - an optional parameter.
	originatorsccpaddressmask - an optional parameter.
	processingtype - an optional parameter.
	errorcode - an optional parameter.
	tlv_<valuetype>_<tagkey> - an optional parameter.
	percent <percent value> - an optional parameter.

	newnetworkid - an optional parameter.
	newdestton - an optional parameter.
	newdestnpi - an optional parameter.
	adddestdigprefix - an optional parameter.
	addsourcedigprefix - an optional parameter.
	newsourceton - an optional parameter.
	newsourcenpi - an optional parameter.
	newsourceaddr - an optional parameter.
	mtlocalsccpgt - an optional parameter.
	mtremotesccptt - an optional parameter.
	makecopy - an optional parameter.
	hrbypass - an optional parameter.
	dropaftersri - an optional parameter.
	newnetworkidaftersri - an optional parameter.
	newnetworkidafterpermfail - an optional parameter.
	dropaftertempfail - an optional parameter.
	newnetworkidaftertempfail - an optional parameter.
	droponarrival - an optional parameter.
	rejectonarrival - an optional parameter.
	remove_tlv - an optional parameter.

EXAMPLES
	smsc mproc modify 1 newnetworkid 13
----

[[_mproc_rule_settings_modify_gui]]
=== Using GUI


. In the GUI Management Console for SMSC Gateway, click on 'Message Processing Rules' in the left panel. 
. The main panel will display the existing mproc rule (if any), one each in a row with corresponding actions (delete, update) for each row.
  Below this you will find the button 'Create Message Processing Rule'. 
. You can modify an existent mproc rule by launching the 'Message Procesing Rule #... properties' window by clicking on the blue coloured 'Modify Message Processing Rule' button.
  The 'Message Procesing Rule #... properties' window will display all proc rule paramters that must be updated by you.
  For more details of these parameters please refer to the descriptions of the CLI commands for the same in the preceding section.
  For customized mproc rules the set of parameters is configured as a plain string. 
. Update appropriate values for all the parameters and then click on the 'Close' button.
  This action will modify a mproc rule with parameters as defined by you. 
. If there is an error in updating the mproc rule, then you will find the details of the error in the Management Console Log section below. 

[[_mproc_rule_settings_view]]
== View a mproc rule details.

[[_mproc_rule_settings_view_cli]]
=== Using CLI

You can view the details of all configured mproc rules or a specified mproc rule by issuing the command smsc mproc show as described below. 

----

Name
	smsc mproc show

SYNOPSIS
	smsc mproc show <id>

DESCRIPTION

	This command is used to list all configured mproc rules
	or a specified mproc rule. Only nondefault mproc rule parameters
	(conditions and actions) will be displayed in the command output.

PARAMETERS

	id - an optional parameter. You can specify this parameter to ask
	detalis for a mproc rule with a provided Id. If you do not
	specify this parameter all mproc rules will be displayed.

EXAMPLES
	smsc mproc show 1
	smsc mproc show
----

[[_mproc_rule_settings_view_gui]]
=== Using GUI


. In the GUI Management Console for SMSC Gateway, click on 'Message Processing Rules' in the left panel. 
. The main panel will display the existing mproc rule (if any), one each in a row with corresponding actions (delete, update) for each row.
  Below this you will find the button 'Create Message Processing Rule'. 
. You can view the details of a mproc rule by clicking on the row corresponding to the mproc rule.
  All relevant details of the mproc rule will be displayed in an expanded format. 

[[_mproc_rule_settings_remove]]
== Remove an existing mproc rule.

[[_mproc_rule_settings_remove_cli]]
=== Using CLI

You can remove an existent mproc rule by issuing the command smsc mproc remove with appropriate parameters as described below. 

----

Name
	smsc mproc remove

SYNOPSIS
	smsc mproc remove <id>

DESCRIPTION

	This command is used to remove an existing mproc rule.

PARAMETERS

	id - a mandatory parameter - id of an existent
	mproc rule to remove.

EXAMPLES
	smsc mproc remove 1
----

[[_mproc_rule_settings_remove_gui]]
=== Using GUI


. In the GUI Management Console for SMSC Gateway, click on 'Message Processing Rules' in the left panel. 
. The main panel will display the existing mproc rule (if any), one each in a row with corresponding actions (delete, update) for each row.
  Below this you will find the button 'Create Message Processing Rule'. 
. To remove an existing mproc rule click on the delete icon marked 'x' in red, for the row corresponding to the mproc rule. 