
[[_mapcache]]
= MAP Version Cache

{this-platform} {this-application} caches the negotiated MAP Version for each network node.
Cache stores the Global Title of SCCP address of the network node.
Every MT SMS sent to this node will use the cached Version.
This will help in reducing the MAP Version negotiation duration everytime and hence improve the performance.

[[_mapcache_cli]]
== Using CLI

You can set the 'MAP Version Cache' value by issuing the command `smsc mapcache set` with appropriate parameters as described below.
You can verify this by issuing the command `smsc mapcache get` which will display all the cached values.
Alternatively you can retrieve the cached value for a specific node by issuing the command `smsc mapcache get <node_digits>`.
You can clear the cache by issuing the command `smsc mapcache clear`. 

----

Name
	smsc mapcache set

SYNOPSIS
	smsc mapcache set <node_digits> <version>

DESCRIPTION
	This command is used to set the version for the specific node digits. SMSC Gateway
	caches the negotiated MAP Version for each network node. Every MT SMS sent to this
	node will use the cached Version.
----

[[_mapcache_gui]]
== Using GUI

.Procedure: Managing MAP Version Cache value using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'MAP Version Cache' in the left panel. 
. You can specify the MAP Application Context version for every node by entering the value for Node Digits and choosing the Version for MAP MtForwardSm operation. 
. You must click on the button 'Update' to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 
. To view the cached version value for a specific node, enter the node digits (under View Cache) and click on the "View" button.
  The cached value will be displayed in the log.
. To clear all the cached values, click on the "Clear Cache" button.
