
= SMSC Gateway Server Settings

[[_smsc_gateway_server_properties]]
== SMSC Server Properties

[[_defaultvalidityperiodhours]]
=== Default Validity Period (in hours)

[[_defaultvalidityperiodhours_cli]]
==== Using CLI

You can set the 'Default Validity Period (in hours)' by issuing the command `smsc set defaultvalidityperiodhours` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get defaultvalidityperiodhours` which will display the value set for this property. 

----

Name
	smsc set defaultvalidityperiodhours

SYNOPSIS
	smsc set defaultvalidityperiodhours <default-validity-period-hours>

DESCRIPTION
	This command is used to set a value for default validity period (in hours) for 
	incoming SMSC messages that do not have their own validity period value. Validity 
	period is the time duration for which the SMSC Gateway will attempt to
	send the SMS. If the time period expires before the message can be delivered, 
	the SMSC Gateway will drop it.

EXAMPLES
	smsc set defaultvalidityperiodhours 3
----

[[_defaultvalidityperiodhours_gui]]
==== Using GUI

.Procedure: Set Default Validity Period using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the default validity period (in hours) by entering the value in the text field 'Default validity period hours (in hours)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_maxvalidityperiodhours]]
=== Maximum Validity Period (in hours)

[[_maxvalidityperiodhours_cli]]
==== Using CLI

You can set the 'Max Validity Period (in hours)' by issuing the command `smsc set maxvalidityperiodhours` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get maxvalidityperiodhours` which will display the value set for this property. 

----

Name
	smsc set maxvalidityperiodhours

SYNOPSIS
	smsc set maxvalidityperiodhours <max-validity-period-hours>

DESCRIPTION
	This command is used to set a value for the maximum validity period (in hours).
	All incoming messages with a validity period set greater than the value specified
	by this parameter will either be rejected (if they are ESME originated messages)
	or the value of their validity period will be set to this value (for MO originated
	messages).

EXAMPLES
	smsc set maxvalidityperiodhours 6
----

[[_maxvalidityperiodhours_gui]]
==== Using GUI

.Procedure: Set Maximum Validity Period using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the maximum validity period (in hours) by entering the value in the text field 'Maximum validity period (in hours)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_defaultton]]
=== Default Type of Number (TON)

[[_defaultton_cli]]
==== Using CLI

You can set the 'Default type of number (TON)' by issuing the command `smsc set defaultton` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get defaultton` which will display the value set for this property. 

----

Name
	smsc set defaultton

SYNOPSIS
	smsc set defaultton <default-ton>

DESCRIPTION
	This command is used to set a value for default TON (Type Of Number). If an
	incoming message does not have a value defined for TON, i.e. if TON is set as
	'unknown', then the value specified for defaultton will be used as TON for that 
	message.

EXAMPLES
	smsc set defaultton 1
----

[[_defaultton_gui]]
==== Using GUI

.Procedure: Set Default type of number (TON) using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the Default type of number (TON) by entering the value in the text field 'Default type of number (TON)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_defaultnpi]]
=== Default numbering plan indicator (NPI)

[[_defaultnpi_cli]]
==== Using CLI

You can set the 'Default numbering plan indicator (NPI)' value by issuing the command `smsc set defaultnpi` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get defaultnpi` which will display the value set for this property. 

----

Name
	smsc set defaultnpi

SYNOPSIS
	smsc set defaultnpi <default-npi>

DESCRIPTION
	This command is used to set a value for default NPI (Number Plan Indicator). If an
	incoming message does not have a value defined for NPI, i.e. if NPI is set as
	'unknown', then the value specified for defaultnpi will be used as NPI for that 
	message.

EXAMPLES
	smsc set defaultnpi 1
----

[[_defaultnpi_gui]]
==== Using GUI

.Procedure: Set Default numbering plan indicator (NPI) using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the Default numbering plan indicator (NPI) by entering the value in the text field 'Default numbering plan indicator (NPI)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_esmedefaultcluster]]
=== Cluster Name

[[_esmedefaultcluster_cli]]
==== Using CLI

You can set the 'Cluster Name' value by issuing the command `smsc set esmedefaultcluster` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get esmedefaultcluster` which will display the value set for this property.
This parameter affects only for DatabaseSmsRoutingRule - see <<_db_routing_rule_settings>>.
----

Name
	smsc set esmedefaultcluster

SYNOPSIS
	smsc set esmedefaultcluster <esme-default-cluster>

DESCRIPTION
	This command is used to set a value for ESME default cluster. If the 
	destination-address does not match to any ESME (any Cluster Name) the message will
	be routed to the cluster with the name specified here for esme-default-cluster.
	This parameter affects only for DatabaseSmsRoutingRule (not used for default
	routing). 
----

You can remove an ESME default cluster by issuing a command in the below format:

----

Name
	smsc remove esmedefaultcluster

SYNOPSIS
	smsc remove esmedefaultcluster <esme-default-cluster>

DESCRIPTION
	This command is used to remove the value configured for ESME default cluster. If 
	this value is removed, all unrouted messages will be routed into the GSM network.
	This parameter affects only for DatabaseSmsRoutingRule (not used for default
	routing). 
----

[[_esmedefaultcluster_gui]]
==== Using GUI

.Procedure: Set Cluster Name using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the Cluster Name by entering the value in the text field 'Cluster Name'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_smpp_encoding_for_ucs2]]
=== SMPP Encoding for GSM7/UCS2

[[_smpp_encoding_for_ucs2_cli]]
==== Using CLI

You can set the 'SMPP Encoding for GSM7 (DCS=0)' and 'SMPP Encoding for UCS2 (DCS=8)' value by issuing the commands `smsc set smppencodingforgsm7` / `smsc set smppencodingforucs2` with appropriate parameters as described below.
You can verify this by issuing the commands `smsc get smppencodingforgsm7` / `smsc get smppencodingforucs2` which will display the value set for these property.
When GSM8 encoding type no recoding of message content is made. 

----

Name
    smsc set smppencodingforgsm7
    smsc set smppencodingforucs2

SYNOPSIS
    smsc set smppencodingforgsm7 <UTF8|UNICODE|GSM7>
	smsc set smppencodingforucs2 <UTF8|UNICODE|GSM7>

DESCRIPTION
    These commands are used to set the Encoding Scheme at SMPP side for
    different GSM data coding schemas (DCS). 
    
    For GSM7 encoding (DCS = 0) you must use the command 
    smsc set smppencodingforgsm7, in order to set text encoding style. 
    
    For UCS2 encoding (DCS = 8), you must use the command
    smsc set smppencodingforucs2, in order to set text encoding style.
    
    At the SMPP side, messages accept 3 different encoding schemes namely UTF8,
    UNICODE and GSM7 (8-bit), for both sending and receiving messages. The SMSC
    can be configured to accept one of them (the one that ESME supports). If this
    is not set, then the default encoding sheme is UTF8. For GSM8 encoding (DCS = 4),
    no charset encoding made in the SMSC. 

EXAMPLES
	smsc set smppencodingforgsm7 utf8 
	or
	smsc set smppencodingforucs2 unicode
----

[[_smpp_encoding_for_ucs2_gui]]
==== Using GUI

.Procedure: Set SMPP Encoding for GSM7 and UCS2 using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the encoding scheme by choosing from the values (UTF8 | UNICODE | GSM7) in the list for 'SMPP Encoding for GSM7' (DCS=0) or 'SMPP Encoding for UCS2' (DCS=8). For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_storeandforwardmode]]
=== Store And Forward Mode

[[_storeandforwordmode_cli]]
==== Using CLI

You can set the 'Store And Forward Mode' value by issuing the command `smsc set storeandforwordmode` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get storeandforwordmode` which will display the value set for this property. 

----

Name
	smsc set storeandforwordmode

SYNOPSIS
	smsc set storeandforwordmode <normal | fast>

DESCRIPTION
	This command is used to set the storeandforwordmode value.
	storeandforwordmode has two possible values:
	
	normal - StoreAndForward mode is used for incoming 
	smpp StoreAndForward messages and all SS7 and SIP messages. All 
	the incoming messages into SMSC will be persisted before trying
	for delivery.

	fast (default) - ForwardAndStore mode is used for incoming smpp
	StoreAndForward messages and all SS7 and SIP messages. This option
	can be switched without SMSC restart. All the incoming messages into
	SMSC will be tried for delivery first and only if delivery fails,
	it will be persisted for later re-try.
	
	Datagramm and Transactional modes will work in the same way for both normal and fast modes. 

EXAMPLES
	smsc get storeandforwordmode fast
----

[[_storeandforwordmode_gui]]
==== Using GUI

.Procedure: Set Store And Forward Mode using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the Store And Forward Mode by selecting the value from the dropdown field 'Store And Forward Mode'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_locking_s_table]]
=== National language locking shift table

[[_locking_s_table_cli]]
==== Using CLI

You can set the 'National language locking shift table' value by issuing the command smsc set nationallanguagelockingshift with appropriate parameters as described below.
You can verify this by issuing the command smsc get nationallanguagelockingshift which will display the value set for this property. 

----

Name
	smsc set nationallanguagelockingshift

SYNOPSIS
	smsc set nationallanguagelockingshift <NationalLanguageIdentifier>

DESCRIPTION
	National language locking shift table can be configured for messages
	that have come via SMPP, do not have UDHs inside and have GSM7 encoding
	(DCS==0).
	The default GSM data coding table is mostly used. Possible values:
	= 0: default GSM data coding table
	= 13: urdu (arabic) national language shift table
	This value can be also configured at ESME level.

EXAMPLES
	smsc set nationallanguagelockingshift 0
	smsc set nationallanguagelockingshift 13
----

[[_locking_s_table_gui]]
==== Using GUI

.Procedure: Set National language locking shift table using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the National language locking shift table by entering the value in the text field 'National language locking shift'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section. 
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_single_s_table]]
=== National language single shift table

[[_single_s_table_cli]]
==== Using CLI

You can set the 'National language single shift table' value by issuing the command smsc set nationallanguagesingleshift with appropriate parameters as described below.
You can verify this by issuing the command smsc get nationallanguagesingleshift which will display the value set for this property. 

----

Name
	smsc set nationallanguagesingleshift

SYNOPSIS
	smsc set nationallanguagesingleshift <NationalLanguageIdentifier>

DESCRIPTION
	National language single shift table can be configured for messages
	that have come via SMPP, do not have UDHs inside and have GSM7 encoding
	(DCS==0).
	The default GSM data coding table is mostly used. Possible values:
	= 0: default GSM data coding table
	= 13: urdu (arabic) national language shift table
	This value can be also configured at ESME level.

EXAMPLES
	smsc set nationallanguagesingleshift 0
	smsc set nationallanguagesingleshift 13
----

[[_single_s_table_gui]]
==== Using GUI

.Procedure: Set National language single shift table using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the National language single shift table by entering the value in the text field 'National language single shift'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section. 
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_subscriberbusyduedelay]]
=== Subscriber busy due delay (in sec)

[[_subscriberbusyduedelay_cli]]
==== Using CLI

You can set the 'Subscriber busy due delay (in sec)' value by issuing the command `smsc set subscriberbusyduedelay` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get subscriberbusyduedelay` which will display the value set for this property. 

----

Name
	smsc set subscriberbusyduedelay

SYNOPSIS
	smsc set subscriberbusyduedelay <subscriber-busy-due-delay>

DESCRIPTION
	This command is used to set a value for subscriber-busy-due-delay (in seconds).
	This parameter specifies the delay time period in seconds when there has
	been a delivery failure with the cause 'subscriber busy'.

EXAMPLES
	smsc set subscriberbusyduedelay 2
----

[[_subscriberbusyduedelay_gui]]
==== Using GUI

.Procedure: Set Subscriber busy due delay (in sec) using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the Subscriber busy due delay by entering the value in the text field 'Subscriber busy due delay (in sec)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_firstduedelay]]
=== First due delay (in sec)

[[_firstduedelay_cli]]
==== Using CLI

You can set the 'First due delay (in sec)' value by issuing the command `smsc set firstduedelay` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get firstduedelay` which will display the value set for this property. 

----

Name
	smsc set firstduedelay

SYNOPSIS
	smsc set firstduedelay <first-due-delay>

DESCRIPTION
	This command is used to set a value for first-due-delay (in seconds). This 
	parameter specifies the delay time period in seconds between message incoming time 
	and first delivery attempt.

EXAMPLES
	smsc set firstduedelay 60
----

[[_firstduedelay_gui]]
==== Using GUI

.Procedure: Set First due delay (in sec) using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the First due delay by entering the value in the text field 'First due delay (in sec)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_secondduedelay]]
=== Second due delay (in sec)

[[_secondduedelay_cli]]
==== Using CLI

You can set the 'Second due delay (in sec)' value by issuing the command `smsc set secondduedelay` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get secondduedelay` which will display the value set for this property. 

----

Name
	smsc set secondduedelay

SYNOPSIS
	smsc set secondduedelay <second-due-delay>

DESCRIPTION
	This command is used to set a value for second-due-delay (in seconds). This 
	parameter specifies the delay time period in seconds between the first and second 
	delivery attempt (i.e. if the first delivery attempt failed).

EXAMPLES
	smsc set secondduedelay 5
----

[[_secondduedelay_gui]]
==== Using GUI

.Procedure: Set Second due delay (in sec) using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the Second due delay by entering the value in the text field 'Second due delay (in sec)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_maxduedelay]]
=== Max due delay (in sec)

[[_maxduedelay_cli]]
==== Using CLI

You can set the 'Max due delay (in sec)' value by issuing the command `smsc set maxduedelay` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get maxduedelay` which will display the value set for this property. 

----

Name
	smsc set maxduedelay

SYNOPSIS
	smsc set maxduedelay <maxduedelay>

DESCRIPTION
	This command is used to set a value for max-due-delay (in seconds). This parameter 
	specifies the maximum possible delay time period in seconds between delivery
	attempts.

EXAMPLES
	smsc set maxduedelay 3600
----

[[_maxduedelay_gui]]
==== Using GUI

.Procedure: Set Max due delay (in sec) using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the Max due delay by entering the value in the text field 'Max due delay (in sec)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_duedelaymultiplicator]]
=== Due delay multiplicator

[[_duedelaymultiplicator_cli]]
==== Using CLI

You can set the 'Due delay multiplicator' value by issuing the command `smsc set duedelaymultiplicator` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get duedelaymultiplicator` which will display the value set for this property. 

----

Name
	smsc set duedelaymultiplicator

SYNOPSIS
	smsc set duedelaymultiplicator <due-delay-multiplicator>

DESCRIPTION
	This command is used to set a value for due-delay-multiplicator. This parameter 
	specifies the delay multiplicator value before another delivery attempt (after 
	failure) is made. 

	After a message delivery failure (if message validity period is not over and the 
	failure is temporary), a delay period is induced before the next delivery attempt.
	This delay period is calculated as follows: 

	Delay after the first delivery failure = 
				second-due-delay

	Delay after every consecutive delivery failure = 
				prev-due-delay * due-delay-multiplicator / 100 
			        where prev-due-delay is the delay at the previous step.

EXAMPLES
	smsc set duedelaymultiplicator 200

	Lets take an example where the First due delay is 60 seconds, Second due delay is
	300 seconds, and the due-delay-multiplicator is 200, the attempts will be made
	as below:

	First attempt will be after 60 seconds (1 min) 
	[delay is configured in First due delay]

	Second attempt will be after 300 seconds (5 min) 
	[delay is configured in Second due delay assuming 
	delivery failed not because of "Subscriber busy"]

	Third attempt will be after 600 sec (10 min) 
	[delay is calculated based on Due delay multiplicator]
	Delay = 300 * 200 / 100	= 600

	Fourth attempt will be after 1200 sec (20 min) 
	[delay is calculated based on Due delay multiplicator]
	Delay = 600 * 200 / 100	= 1200

	Fifth attempt will be after 2400 sec (40 min) 
	[delay is calculated based on Due delay multiplicator]
	Delay = 1200 * 200 / 100 = 2400
----

[[_duedelaymultiplicator_gui]]
==== Using GUI

.Procedure: Set Due delay multiplicator using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the Due delay multiplicator by entering the value in the text field 'Due delay multiplicator'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 


[[_vpprolong]]
=== Validity period scheduling prolongation

[[_vpprolong_cli]]
==== Using CLI

You can set the 'Validity period scheduling prolongation (sec)' value by issuing the command `smsc set vpprolong` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get vpprolong` which will display the value set for this property. 

----

Name
	smsc set vpprolong

SYNOPSIS
	smsc set vpprolong <vpprolong>

DESCRIPTION
	This command is used to set the value of Validity period scheduling
	prolongation in seconds.
	Conditions when a message with validity period will be scheduled after delivery
	failure:
	a) validity period end time >= the time for next schedule time
	or
	b) validity period end time >= now + Validity period scheduling prolongation
	By changing of "Validity period scheduling prolongation" you can specify will
	a message be scheduled after validity period end time or not.
	Setting this parameter to 0 lead that all messages will be scheduled.
	Setting this parameter to a very big value lead that no message will be scheduled.
	The general rule is - you can allow messages to be scheduled for after validity
	period end time when scheduling is for for after long time from now.
	Default value: 120 (seconds).

EXAMPLES
	smsc set vpprolong 120
----

[[_vpprolong_gui]]
==== Using GUI

.Procedure: Set Validity period scheduling prolongation using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Properties' tab in the GUI. 
. You can specify the Validity period scheduling prolongation by entering the value in the text field 'Validity period scheduling prolongation (sec)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 


[[_smsc_ss7_settings]]
== SS7 Settings

[[_set_scgt]]
=== SMSC Gateway Global Title

[[_set_scgt_cli]]
==== Using CLI

You can set the 'SMSC Gateway Global Title' by issuing the command `smsc set scgt` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get scgt` which will display the value set for this property. 

----

Name
        smsc set scgt

SYNOPSIS
        smsc set scgt <globalTitle> networkid <networkId>

DESCRIPTION
        This command is used to set a value for SMSC Global Title.

        networkId - a specifies Global Title for a virtual SS7
        subnetwork (this is for Multi-tenancy support). By using of
        this command with different networkIds you can specify
        Global Titles for several subnetworks. 
        If this parameter is skipped - networkId will be set to "0"
        when Global Title creation (master networkId).
        When we do not specify Global Title for some networkid -
        Global Title for master networkId will be used. When we
        use "0" as Global Title value 
        (like "smsc set scgt 0 networkid <xxx>") -
        this will just clear Global Title for an specified networkid.
----

[[_set_scgt_gui]]
==== Using GUI

.Procedure: Set SMSC Global Title using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'SS7 Settings' tab in the GUI. 
. You can specify the SMSC Global Title by entering values into fields pair 'SMSC Gateway Global Title Indicator Network Id' and 'SMSC Gateway Global Title'. You are able to set Global Title for definite networkId.
  Setting of Global Title for networkId to "0" leads clearing of Global Title for networkId.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_set_gti]]
=== SMSC Gateway Global Title Indicator

[[_set_gti_cli]]
==== Using CLI

You can set the 'SMSC Gateway Global Title Indicator' by issuing the command `smsc set gti` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get gti` which will display the value set for this property. 

----

Name
        smsc set gti

SYNOPSIS
        smsc set gti 0001|0010|0011|0100

DESCRIPTION
        This command is used to set the value of SMSC Gateway Global Title 
        Indicator.
        This Global Title Indicator will be used for SCCP outgoing messages.
        Default value for ITU-T is 0100.
        Global title 0001 - Nature of address indicator included
        Global title 0010 - Translation type included
        Global title 0011 - Translation type, Numbering plan and Encoding
                            scheme included
        Global title 0100 - Translation type, Numbering plan, Encoding
                            scheme and Nature of address indicator included
----

[[_set_gti_gui]]
==== Using GUI

.Procedure: Set SCCP Global Title type using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'SS7 Settings' tab in the GUI. 
. You can specify the SCCP Global Title type by entering the value in the text field 'SMSC Gateway Global Title Indicator'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_set_tt]]
=== SMSC Gateway Global Title - Translation Type

[[_set_tt_cli]]
==== Using CLI

You can set the 'SMSC Gateway Global Title - Translation Type' by issuing the command `smsc set tt` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get tt` which will display the value set for this property. 

----

Name
        smsc set tt

SYNOPSIS
        smsc set tt <translation type value>

DESCRIPTION
        This command is used to set the value of SCCP translation type
        value. Translation type value will be used for SCCP outgoing
        messages. Default value for ITU-T is 0.
----

[[_set_tt_gui]]
==== Using GUI

.Procedure: Set SCCP translation type value using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'SS7 Settings' tab in the GUI. 
. You can specify the SCCP translation type value by entering the value in the text field 'SMSC Gateway Global Title - Translation Type'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_set_scssn]]
=== SMSC Sub System Number (SSN)

[[_set_scssn_cli]]
==== Using CLI

You can set the 'SMSC SSN' by issuing the command `smsc set scssn` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get scssn` which will display the value set for this property. 

----

Name
        smsc set scssn

SYNOPSIS
        smsc set scssn <smscSubSystemNumber>

DESCRIPTION
        This command is used to set the value of SMSC Sub System Number (SSN). Issuing 
        this command in CLI will set the SSN value but you must ensure that the SSN number
        is properly configured in the TCAP Stack in the xml descriptor file
        "mobicents-smscgateway-version/jboss-5.1.0.GA/server/default/deploy/
        mobicents-smsc-server/META-INF/jboss-beans.xml".
----

[[_set_scssn_gui]]
==== Using GUI

.Procedure: Set SMSC Sub System Number (SSN) using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'SS7 Settings' tab in the GUI. 
. You can specify the SMSC Sub System Number (SSN) by entering the value in the text field 'SMSC Gateway subsystem number'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_set_hlrssn]]
=== HLR Sub System Number (HLR SSN)

[[_set_hlrssn_cli]]
==== Using CLI

You can set the 'HLR SSN' by issuing the command `smsc set hlrssn` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get hlrssn` which will display the value set for this property. 

----

Name
        smsc set hlrssn

SYNOPSIS
        smsc set hlrssn <hlrSubSystemNumber>

DESCRIPTION
        This command is used to set the value of HLR Sub System Number (SSN).
----

[[_set_hlrssn_gui]]
==== Using GUI

.Procedure: Set HLR Sub System Number (SSN) using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'SS7 Settings' tab in the GUI. 
. You can specify the HLR Sub System Number (SSN) by entering the value in the text field 'HLR subsystem number'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_set_mscssn]]
=== MSC Sub System Number (SSN)

[[_set_mscssn_cli]]
==== Using CLI

You can set the 'MSC SSN' by issuing the command `smsc set mscssn` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get mscssn` which will display the value set for this property. 

----

Name
        smsc set mscssn

SYNOPSIS
        smsc set mscssn <mscSubSystemNumber>

DESCRIPTION
        This command is used to set the value of MSC Sub System Number (SSN).
----

[[_set_mscssn_gui]]
==== Using GUI

.Procedure: Set MSC Sub System Number (SSN) using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'SS7 Settings' tab in the GUI. 
. You can specify the MSC Sub System Number (SSN) by entering the value in the text field 'MSC subsystem number'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_set_maxmapv]]
=== MAP Application Context version

[[_set_maxmapv_cli]]
==== Using CLI

You can set the 'MAP Application Context version' by issuing the command `smsc set maxmapv` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get maxmapv` which will display the value set for this property. 

----

Name
        smsc set maxmapv

SYNOPSIS
        smsc set maxmapv <version-number>

DESCRIPTION
        This command is used to set the value of MAP Application Context version. The
        version number set here will be used for SMS messages exchanged. RestComm SMSC
        Gateway supports version negotiation. So if you set this to a higher version (say
        for example version 3, however your network only understands version 2), the SMSC Gateway
        will automatically do the version negotiation and exchange V2 messages when V3
        exchange fails. However this causes additional messages to be exchanged and
        increases the overall load on the system. Therefore it is advisable to always set
        the correct version.
----

[[_set_maxmapv_gui]]
==== Using GUI

.Procedure: Set MAP Application Context version using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'SS7 Settings' tab in the GUI. 
. You can specify the MAP Application Context version by entering the value in the text field 'MAP version supported'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_set_maxmessagelengthreducer]]
=== Max Message Length Reducer

[[_set_maxmessagelengthreducer_cli]]
==== Using CLI

You can set the 'Max Message Length Reducer' value by issuing the command `smsc set maxmessagelengthreducer` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get maxmessagelengthreducer` which will display the value set for this property. 

----

Name
	smsc set maxmessagelengthreducer

SYNOPSIS
	smsc set maxmessagelengthreducer <max-message-length-reducer>

DESCRIPTION
	This command is used to set an integer value for max-message-length-reducer.
	The recommended value is 6. Possible values are numbers from 0 to 12. 

	Empty TC-BEGIN will be used if the message length is greater than the maximum
	possible message length minus the value specified for max-message-length-reducer.

	(message-length > max-possible-message-length - max-message-length-reducer) 

	Empty TC-BEGIN is used in MAP Version 2 and 3 for forwardSM and Mt-ForwardSM 
	requests. In MAP Version 2 the dailog portion
	(ApplicationContextName, MAPOpenInfo primitive) and the component portion 
	(forwardSM and mt-ForwardSM requests) may both together be too long to fit within 
	a MTP message. In Empty TC-BEGIN case, it first sends the dailog portion in 
	TC-BEGIN followed by the component portion in the next TC-CONTINUE. 
	Whether empty TC-BEGIN is used or not depends on the length of a message and the 
	length of SCCP addresses. This option increases the guarantee of delivery of a 
	message  to some network.

EXAMPLES
	smsc set maxmessagelengthreducer 6
----

[[_set_maxmessagelengthreducer_gui]]
==== Using GUI

.Procedure: Set Max Message Length Reducer using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'SS7 Settings' tab in the GUI. 
. You can specify the Max Message Length Reducer by entering the value in the text field 'Max Message Length Reducer'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_hrhlrnumber_sri]]
=== Pre-configured HLR address for SRI requests

[[_set_hrhlrnumber_sri_cli]]
==== Using CLI

You can set a pre-configured HLR address for SRI requests by issuing the command `smsc set hrhlrnumber` with appropriate parameters as described below.
You can remove this pre-configured address by issuing the command `smsc remove hrhlrnumber`.
You can verify this by issuing the command `smsc get hrhlrnumber` which will display the value set for this property. 

----

Name
	smsc set hrhlrnumber
	smsc remove hrhlrnumber

SYNOPSIS
	smsc set hrhlrnumber <hlr GT digits> networkid <networkId>
	smsc remove hrhlrnumber networkid <networkId>

DESCRIPTION
	This command is used to set a pre-configured HLR address for SRI requests.

	In some scenarios it may be required to set a HLR address instead of a
	MSISDN address into the SCCP 'CalledPartyAddress' of 'SendRoutingInfo'
	requests issued by the SMSC GW in both mobile terminated and home routing
	modes. In such cases, you must set this parameter 'hrhlrnumber' to a 
	pre-configured HLR address. 

	For all other scenarios where this is not required, you may leave this
	parameter empty. When this is empty, the SCCP 'CalledPartyAddress' of 
	'SendRoutingInfo' request will be set to the destination MSISDN of a 
	subscriber.

	networkId - specifies a virtual SS7 subnetwork (this is for Multi-tenancy
	support). By using of this command with different networkIds you can
	specify hrhlrnumber for several subnetworks. 
	If this parameter is skipped - networkId will be set to "0".
----

[[_set_hrhlrnumber_sri_gui]]
==== Using GUI

.Procedure: Set Pre-configured HLR address for SRI requests using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'SS7 Settings' tab in the GUI. 
. You can specify (set or remove) the "Pre-configured HLR address for SRI requests" by entering appropriate values for a specified networkID. Select needed "Pre-configured HLR address for SRI requests Network Id" field value or type a new networkId value if no such value already specifyied. Then type needed HLR address into below field.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_set_sriresponselivetime]]
=== SRI responses Cache Time (in secs)

[[_set_sriresponselivetime_cli]]
==== Using CLI

You can set a SRI responses Cache Time by issuing the command `smsc set sriresponselivetime` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get sriresponselivetime` which will display the value set for this property. 

----

Name
	smsc set sriresponselivetime

SYNOPSIS
	smsc set sriresponselivetime <time in seconds>

DESCRIPTION
	This command is used to set a SRI responses Cache Time.

	SMSC GW can store successfull SendRoutinInfo (SRI) responses (with IMSI and
	NetworkNodeNumber data) into an internal cach for some configurable time.
	SMSC GW	parameter "sriresponselivetime" specifies the minimum time value
	for storing of a response. Caching of SRI responses takes some system
	resources and is recommended only if you need it for some scenarious (like
	you send firstly only an SRI request and do not deliver a message just to
	understend IMSI / NetworkNodeNumber (this scenario is achieavable by mproc
	rules) and then send a message in short time if needed). 

DEFAULT VALUE
	0 - this means no caching.

EXAMPLES
	smsc set sriresponselivetime 0
----

[[_set_sriresponselivetime_gui]]
==== Using GUI

.Procedure: Set SRI responses Cache Time using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'SS7 Settings' tab in the GUI. 
. You can specify (set or remove) the "SRI responses Cache Time (in secs)" by entering appropriate values.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_smsc_db_settings]]
== Cassandra Settings

You can manage Cassandra Settings using the CLI or GUI.
Note that the modified settings will become effective only when the SMSC is re-started.

[[_db_host]]
=== Cassandra Configuration - Host Addresses

[[_db_host_cli]]
==== Using CLI

You can set the 'host addresses' value for Cassandra settings by issuing the command `smsc set dbhosts` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get dbhosts` which will display the value set for this property. 

----

Name
	smsc set dbhosts

SYNOPSIS
	smsc set dbhosts <host-ip>

DESCRIPTION
	This command is used to set the host-ip addresses for Cassandra Database access.

EXAMPLES
	smsc set dbhosts 127.0.0.1
----

[[_db_host_gui]]
==== Using GUI

.Procedure: Set Cassandra Configuration - Host Addresses using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Cassandra' tab in the GUI. 
. You can specify the host-ip address by entering appropriate values in the text field 'Host Address'. For more details of these parameters, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_db_port]]
=== Cassandra Configuration - Port

[[_db_port_cli]]
==== Using CLI

You can set the 'port' value for Cassandra settings by issuing the command `smsc set dbport` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get dbport` which will display the value set for this property. 

----

Name
    smsc set dbport

SYNOPSIS
    smsc set dbport <port>

DESCRIPTION
	This command is used to set the host-ip address for Cassandra Database
	access. Pass comma separated values if Cassandra is setup in cluster
	and can be accessed via multiple IP's

EXAMPLES
    smsc set dbport 9042
----

[[_db_port_gui]]
==== Using GUI

.Procedure: Set Cassandra Configuration - Port using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Cassandra' tab in the GUI. 
. You can specify the host-ip address and port by entering appropriate values in the text field 'Port'. For more details of these parameters, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_db_keyspace]]
=== Cassandra Configuration - Keyspace Name

[[_db_keyspace_cli]]
==== Using CLI

You can set the 'DB Keyspace Name' by issuing the command `smsc set keyspacename` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get keyspacename` which will display the value set for this property. 

----

Name
	smsc set keyspacename

SYNOPSIS
	smsc set keyspacename <keyspacename>

DESCRIPTION
	This command is used to set the Keyspace name for Cassandra Database. If you use
	the script available in the distributive the name will be set to 'RestCommSMSC' by
	default.
----

[[_db_keyspace_gui]]
==== Using GUI

.Procedure: Set Cassandra Configuration - Keyspace Name using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Cassandra' tab in the GUI. 
. You can specify the Keyspace Name by entering the value in the text field 'Keyspace Name'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_db_cluster]]
=== Cassandra Configuration - Cluster Name

[[_db_cluster_cli]]
==== Using CLI

You can set the 'DB Cluster Name' value by issuing the command `smsc set clustername` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get clustername` which will display the value set for this property. 

----

Name
	smsc set clustername

SYNOPSIS
	smsc set clustername <cluster-name>

DESCRIPTION
	This command is used to set the Cluster name for Cassandra Database. If you use
	the script available in the distributive the name will be set to 'RestCommSMSC' by
	default. 

EXAMPLES
	smsc set clustername RestCommSMSC
----

[[_db_cluster_gui]]
==== Using GUI

.Procedure: Set Cassandra Configuration - Cluster Name using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Cassandra' tab in the GUI. 
. You can specify the Cluster Name by entering the value in the text field 'Cluster Name'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[cassandra_user]]
=== Cassandra Configuration - User Name

[[_cassandra_user_cli]]
==== Using CLI

You can set the 'Cassandra User Name' by issuing the command `smsc set cassandrauser` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get cassandrauser` which will display the value set for this property.

----

Name
	smsc set cassandrauser

SYNOPSIS
	smsc set cassandrauser <username>

DESCRIPTION
	This command is used to set the user name for Cassandra Database. Default user is `cassandra`
	You must restart SMSC GW to take effect.

----

[[_cassandra_user_gui]]
==== Using GUI

.Procedure: Set Cassandra Configuration - User Name using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel.
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Cassandra' tab in the GUI.
. You can specify the User Name by entering the value in the text field 'User Name'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below.

[[cassandra_pass]]
=== Cassandra Configuration - Password

[[_cassandra_pass_cli]]
==== Using CLI

You can set the 'Cassandra Password' by issuing the command `smsc set cassandrapass` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get cassandrapass` which will display the value set for this property.

----

Name
	smsc set cassandrapass

SYNOPSIS
	smsc set cassandrapass <password>

DESCRIPTION
	This command is used to set the password for Cassandra Database. Default password is `cassandra`
	You must restart SMSC GW to take effect.

----

[[_cassandra_user_gui]]
==== Using GUI

.Procedure: Set Cassandra Configuration - Password using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel.
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Cassandra' tab in the GUI.
. You can specify the Cassandra Password by entering the value in the text field 'Password'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below.

[[_db_removinglivetablesdays]]
=== Cassandra Configuration - Removing Live Tables Days

[[_db_removinglivetablesdays_cli]]
==== Using CLI

You can set the 'Removing Live Tables Days' value by issuing the command `smsc set removinglivetablesdays` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get removinglivetablesdays` which will display the value set for this property. 

----

Name
	smsc set removinglivetablesdays

SYNOPSIS
	smsc set removinglivetablesdays <value>

DESCRIPTION
	This command is used to configure the SMSC to automatically drop LIVE tables from 
	the Cassandra Database. The SMSC will attempt to delete tables just after
	midnight and after every SMSC restart.

PARAMETERS
	removinglivetablesdays		- This parameter is used to specify the number
					  of days the LIVE tables should be kept before 
					  attempting to drop them automatically.

					  If this value is specified as "0", the SMSC
					  will not drop tables automatically. In this case
					  you must manually drop tables.

					  You must specify a value of 3 or more. You can
					  not set this value to 1 or 2 days. This is to 
					  ensure the tables will be kept for a minimum
					  of 2 days after creation date.

					  The SMSC wil attempt to delete tables for one 
					  day. If the Cassandra Database keeps tables for 
					  older days, then the administrator should drop 
					  these manually.
----

[[_db_removinglivetablesdays_gui]]
==== Using GUI

.Procedure: Set Cassandra Configuration - Removing Live Tables Days
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Cassandra' tab in the GUI. 
. You can specify the Removing Live Tables Days by entering the value in the text field 'Removing Live Tables Days'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_db_removingarchivetablesdays]]
=== Cassandra Configuration - Removing Live Tables Days

[[_db_removingarchivetablesdays_cli]]
==== Using CLI

You can set the 'Removing Live Tables Days' value by issuing the command `smsc set removingarchivetablesdays` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get removingarchivetablesdays` which will display the value set for this property. 

----

Name
	smsc set removingarchivetablesdays

SYNOPSIS
	smsc set removingarchivetablesdays <value>

DESCRIPTION
	This command is used to configure the SMSC to automatically drop ARCHIVE tables 
	from the Cassandra Database. The SMSC will attempt to delete tables just after
	midnight and after every SMSC restart.

PARAMETERS
	removingarchivetablesdays	- This parameter is used to specify the number
					  of days the ARCHIVE tables should be kept before 
					  attempting to drop them automatically.

					  If this value is specified as "0", the SMSC
					  will not drop tables automatically. In this case
					  you must manually drop tables.

					  You must specify a value of 3 or more. You can
					  not set this value to 1 or 2 days. This is to 
					  ensure the tables will be kept for a minimum
					  of 2 days after creation date.

					  The SMSC wil attempt to delete tables for one 
					  day. If the Cassandra Database keeps tables for 
					  older days, then the administrator should drop 
					  these manually.
----

[[_db_removingarchivetablesdays_gui]]
==== Using GUI

.Procedure: Set Cassandra Configuration - Removing Archive Tables Days
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Cassandra' tab in the GUI. 
. You can specify the Removing Archive Tables Days by entering the value in the text field 'Removing Archive Tables Days'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_smsc_scheduler_settings]]
== Scheduler Settings

You can modify Scheduler settings using the CLI or GUI.
The modified settings for Fetch Period will become effective only when the SMSC is re-started.
However modified settings for Max Rows and Max Activity Count will take effect immediately.

[[_fetch_period]]
=== Fetch Period (in ms)

[[_fetch_period_cli]]
==== Using CLI

You can set the 'Fetch Period' value by issuing the command `smsc set fetchperiod` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get fetchperiod` which will display the value set for this property. 

----

Name
	smsc set fetchperiod

SYNOPSIS
	smsc set fetchperiod <fetch-period>

DESCRIPTION
	This command is used to set the fetch period value in milli-seconds for the
	Cassandra database. The parameter fetch-period specifies the time 
	period (in milli-seconds) of fetching messages for delivery from the database.
	The default value is 5 seconds.

EXAMPLES
	smsc set fetchperiod 5000
----

[[_fetch_period_gui]]
==== Using GUI

.Procedure: Set Cassandra Configuration - Cluster Name using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Scheduler' tab in the GUI. 
. You can specify the Fetch Period by entering the value in the text field 'Fetch Period (in ms)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_max_rows]]
=== Max Rows

[[_max_rows_cli]]
==== Using CLI

You can set the 'Max Rows' value by issuing the command `smsc set fetchmaxrows` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get fetchmaxrows` which will display the value set for this property. 

----

Name
	smsc set fetchmaxrows

SYNOPSIS
	smsc set fetchmaxrows <fetch-max-rows>

DESCRIPTION
	This command is used to set the maximum message fetching count for every fetching
	step from the database.
	The default value is 100 messages.

EXAMPLES
	smsc set fetchmaxrows 200
----

[[_max_rows_gui]]
==== Using GUI

.Procedure: Set Max Rows using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Scheduler' tab in the GUI. 
. You can specify the Max Rows by entering the value in the text field 'Max Rows'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_max_activity_count]]
=== Max Activity Count

[[_max_activity_count_cli]]
==== Using CLI

You can set the 'Max Activity Count' value by issuing the command `smsc set maxactivitycount` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get maxactivitycount` which will display the value set for this property. 

----

Name
	smsc set maxactivitycount

SYNOPSIS
	smsc set maxactivitycount <max-activity-count>

DESCRIPTION
	This command is used to set the maximum count of delivering activities that are 
	possible at the same time. 'Count of delivering activities' means the count of 
	messages that are in the state 'delivering' (messages that are fetched from the 
	database and may be already sent or are going to be sent but 
	no delivery acception/rejection has been received). 
	When the delivery process of a message is in progress, field LIVE.IN_SYSTEM==2.

EXAMPLES
	smsc set maxactivitycount 500
----

[[_max_activity_count_gui]]
==== Using GUI

.Procedure: Set Max Activity Count using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Scheduler' tab in the GUI. 
. You can specify the Max Activity Count by entering the value in the text field 'Max Activity Count'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_revisesecondsonsmscstart]]
=== Revise period after SMSC restart

[[_revisesecondsonsmscstart_cli]]
==== Using CLI

You can set the 'Revise period (in seconds) after SMSC restart' value by issuing the command `smsc set revisesecondsonsmscstart` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get revisesecondsonsmscstart` which will display the value set for this property.
If unspecified, the default value for this parameter is 60 seconds. 

----

Name
	smsc set revisesecondsonsmscstart <seconds>

SYNOPSIS
	smsc set revisesecondsonsmscstart <seconds>

DESCRIPTION
	This command is used to set the revise period (in seconds). After every restart,
	the SMSC Gateway will revise the last 'x' seconds before shutdown to ensure that
	all the arrived messages are processed; where 'x' is the value set in seconds
	for the parameter 'revisesecondsonsmscstart' using this command.
EXAMPLES
	smsc set revisesecondsonsmscstart 30
----

[[_revisesecondsonsmscstart_gui]]
==== Using GUI

.Procedure: Set Revise Period using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Scheduler' tab in the GUI. 
. You can specify the revise period in seconds by entering the value in the text field 'Revise period after SMSC restart (sec)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_processingsmssettimeout]]
=== Cache timeout period

[[_processingsmssettimeout_cli]]
==== Using CLI

You can set the 'Cache timeout period' value by issuing the command `smsc set processingsmssettimeout` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get processingsmssettimeout` which will display the value set for this property.
If unspecified, the default value for this parameter is 600 seconds.
Generally, you may not have to modify this value. 

----

Name
	smsc set processingsmssettimeout <seconds>

SYNOPSIS
	smsc set processingsmssettimeout <seconds>

DESCRIPTION
	This command is used to set the Cache timeout period (in seconds). 
	Messages are cached in the SMSC until the processing is completed. In case of a 
	delivery failure, these cached messages are force cleaned by the SMSC after 
	waiting for the timeout period set for the parameter 'processingsmssettimeout' 
	using this command.
EXAMPLES
	smsc set processingsmssettimeout 45
----

[[_processingsmssettimeout_gui]]
==== Using GUI

.Procedure: Set Cache timeout Period using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Scheduler' tab in the GUI. 
. You can specify the Cache timeout period in seconds by entering the value in the text field 'Processing Sms set cache timeout (sec)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_deliverytimeout]]
=== Delivery timeout

[[_deliverytimeout_cli]]
==== Using CLI

You can set the 'Delivery timeout' value by issuing the command `smsc set deliverytimeout` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get deliverytimeout` which will display the value set for this property.
If unspecified, the default value for this parameter is 600 seconds.
Generally, you may not have to modify this value. 

----

Name
	smsc set deliverytimeout

SYNOPSIS
	smsc set deliverytimeout <delivery-timeout>

DESCRIPTION
	This command is used to set a length of delivery process timeout
	in seconds. Timeout occurs if no actions for delivering (delivery confirmation
	or a new item delivery) for long time). If the timeout occurs SMSC GW will
	terminate delivery process.
	Default value: 120 seconds.

EXAMPLES
	smsc set deliverytimeout 120
----

[[_deliverytimeout_gui]]
==== Using GUI

.Procedure: Set Delivery timeout using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Scheduler' tab in the GUI. 
. You can specify the Delivery timeout in seconds by entering the value in the text field 'Delivery timeout (sec)'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 







[[_smsc_gateway_server_skip_diue_slot]]
=== Skipping of scheduled for the past and not yet sent messages ("In process" due_slot shifting).

[[_smsc_gateway_server_skip_diue_slot_cli]]
==== Using CLI

This command will skip of processing / fetching of messages that was scheduled for delivering for the time in the past but have not yet delivered by SMSC GW because of SMSC GW was turned off or overloaded.
<time in seconds> means the point of the time (actual current time - <time in seconds>) to which the point of processing / fetching of messages will be shifted.
If the value "0" is provided this means SMSC GW will be shifted into an actual (current) time ("in process" due_slot will be shifted to "in time" due_slot). If the value is positive this means SMSC GW "in process" due_slot will be shifted into a some time in the past (for example if the value is 3600 - to the time before the current time ("in time" due_slot) for 1 hour). Negative values are not accepted.
"In process" due_slot can be shifted only forward.
It is not possible to shift "in process" due_slot backward (and resend messages that was already sent once). 

----

Name
    smsc skipunsentmessages

SYNOPSIS
    smsc skipunsentmessages <time in seconds>

DESCRIPTION
	Executing of this command leads SMSC GW to switch "In process" due_slot
	forward to the current time or to some time before the current time.
	This is possible only if there is some lag in message processing by
	SMSC GW. This also leads of skipping of sending messages that were
	scheduled for time in the past but have not delivered so far.

EXAMPLES
	smsc skipunsentmessages 0
----

[[_smsc_gateway_server_skip_diue_slot_gui]]
==== Using GUI

.Procedure: Skipping of scheduled for the past and not yet sent messages ("In process" due_slot shifting) by the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Scheduler' tab in the GUI. 
. Set "Skip Unsent Messages (in sec) " field to 0 or positive value. 
. You must click on the button 'Save' that is below to skip scheduled messages.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_smsc_diameter_settings]]
== Diameter Settings

You can modify Diameter settings using the CLI or GUI.

[[_dest_realm]]
=== Destination Realm

[[_dest_realm_cli]]
==== Using CLI

You can set the 'Destination Realm' value by issuing the command `smsc set diameterdestrealm` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get diameterdestrealm` which will display the value set for this property. 

----

Name
	smsc set diameterdestrealm

SYNOPSIS
	smsc set diameterdestrealm <value>

DESCRIPTION
	This command is used to set the Diameter Destination Realm for connection to OCS.
	Default value is "mobicents.org".

EXAMPLES
	smsc set diameterdestrealm mobicents.org
----

[[_dest_realm_gui]]
==== Using GUI

.Procedure: Set Diameter Destination Realm using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Diameter' tab in the GUI. 
. You can specify the Destination Realm by entering the value in the corresponding text field.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_dest_host]]
=== Destination Host

[[_dest_host_cli]]
==== Using CLI

You can set the 'Destination Host' value by issuing the command `smsc set diameterdesthost` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get diameterdesthost` which will display the value set for this property. 

----

Name
	smsc set diameterdesthost

SYNOPSIS
	smsc set diameterdesthost <value>

DESCRIPTION
	This command is used to set the Diameter Destination Host for connection to OCS.
    Default value is "127.0.0.1".

EXAMPLES
	smsc set diameterdesthost 127.0.0.1
----

[[_dest_host_gui]]
==== Using GUI

.Procedure: Set Diameter Host using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Diameter' tab in the GUI. 
. You can specify the Destination Host by entering the value in the corresponding text field.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_dest_port]]
=== Destination Port

[[_dest_port_cli]]
==== Using CLI

You can set the 'Destination Port' value by issuing the command `smsc set diameterdestport` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get diameterdestport` which will display the value set for this property. 

----

Name
	smsc set diameterdestport

SYNOPSIS
	smsc set diameterdestport <value>

DESCRIPTION
	This command is used to set the Diameter Destination Port for connection to OCS.
    Default value is 3868.

EXAMPLES
	smsc set diameterdestport 3868
----

[[_dest_port_gui]]
==== Using GUI

.Procedure: Set Diameter Port using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Diameter' tab in the GUI. 
. You can specify the Destination Port by entering the value in the corresponding text field.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_dest_username]]
=== Destination Username

[[_dest_username_cli]]
==== Using CLI

You can set the 'Destination Username' value by issuing the command `smsc set diameterusername` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get diameterusername` which will display the value set for this property. 

----

Name
	smsc set diameterusername

SYNOPSIS
	smsc set diameterusername <value>

DESCRIPTION
	This command is used to set the Diameter Username for connection to OCS.

EXAMPLES
	smsc set diameterdestusername svinu
----

[[_dest_username_gui]]
==== Using GUI

.Procedure: Set Diameter Username using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Diameter' tab in the GUI. 
. You can specify the Username by entering the value in the corresponding text field.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_dest_mocharging]]
=== MO accepting and charging settings

[[_dest_mocharging_cli]]
==== Using CLI

You can set the 'MO (mobile originated) Charging' value by issuing the command `smsc set mocharging` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get mocharging` which will display the value set for this property. 

----

Name
	smsc set mocharging

SYNOPSIS
	smsc set mocharging <accept|reject|diameter>

DESCRIPTION
    This command is used to set the value of the parameter 'moCharging' to
    an appropriate value. This value is set to "accept" by default.
    - accept - all Mobile Originated messages are accepted
    - reject - all Mobile Originated messages are rejected
    - diameter - all Mobile Originated messages are charged by OCS via
      Diameter, prior to being sent

EXAMPLES
	smsc set mocharging accept
----

[[_dest_mocharging_gui]]
==== Using GUI

.Procedure: Set MO Charge using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Diameter' tab in the GUI. 
. You can set 'Mobile Originated SMS Charged' value to true or false, in the corresponding list.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_dest_txsmppcharging]]
=== ESME Charge Settings

[[_dest_txsmppcharging_cli]]
==== Using CLI

You can set the 'ESME Originated SMS Charged' value by issuing the command `smsc set txsmppcharging` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get txsmppcharging` which will display the value set for this property. 

----

Name
	smsc set txsmppcharging

SYNOPSIS
	smsc set txsmppcharging <None|Selected|All>

DESCRIPTION
	This command is used to set the value of the parameter 'txsmppcharging' to None,
	Selected or All. 

	If this is set to 'Aall', all ESME Originated messages will be charged by OCS via
	Diameter, prior to being sent.

	If this is set to 'Selected', only those messages originating from ESMEs marked 
	with the parameter 'charging-enabled'=true at the time of ESME creation  will be 
	charged by OCS via Diameter, prior to being sent.

	If this is set to 'None', none of the ESME Originated messages will be charged by 
	OCS via Diameter, prior to being sent. 

	The parameter 'txsmppcharging' is set to 'None' by default.

EXAMPLES
	smsc set txsmppcharging Selected
----

[[_dest_txsmppcharging_gui]]
==== Using GUI

.Procedure: Set ESME Charge using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Diameter' tab in the GUI. 
. You can set 'ESME Originated SMS Charged' value to none, selected or all, in the corresponding list.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_dest_txsipcharging]]
=== SIP Charge Settings

[[_dest_txsipcharging_cli]]
==== Using CLI

You can set the 'SIP Originated SMS Charged' value by issuing the command `smsc set txsipcharging` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get txsipcharging` which will display the value set for this property. 

----

Name
    smsc set txsipcharging

SYNOPSIS
    smsc set txsipcharging <None|Selected|All>

DESCRIPTION
	This command is used to set the value of the parameter 'txsipcharging' 

	If this is set to 'All', all SIP Originated messages will be charged by OCS via
	Diameter, prior to being sent.

	If this is set to 'None' or 'Selected', none of the SIP Originated messages will
	be charged by OCS via Diameter, prior to being sent. 

    The parameter 'txsipcharging' is set to 'None' by default.

EXAMPLES
    smsc set txsipcharging Selected
----

[[_dest_txsipcharging_gui]]
==== Using GUI

.Procedure: Set SIP Charge using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Diameter' tab in the GUI. 
. You can set 'SIP Originated SMS Charged' value to none, selected or all, in the corresponding list.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_dest_hrcharging]]
=== Home routing Charge Settings

[[_dest_hrcharging_cli]]
==== Using CLI

You can set the 'Home routing Originated SMS Charged' value by issuing the command `smsc set hrcharging` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get hrcharging` which will display the value set for this property. 

----

Name
    smsc set hrcharging

SYNOPSIS
    smsc set hrcharging <accept|reject|diameter>

DESCRIPTION
    This command is used to set the value of the parameter 'hrcharging' to 
    an appropriate value. This value is set to "accept" by default. This
    option works like mocharging option but affects on SS7 messages in home
    routing mode from upper SMSC (mocharging affects on mobile originated
    SS7 incoming messages).
    - accept - all Home Routing originated messages are accepted
    - reject - all Home Routing originated messages are rejected
    - diameter - all Home Routing Originated messages are charged by OCS via
      Diameter, prior to being sent

EXAMPLES
    smsc set hrcharging accept
----

[[_dest_hrcharging_gui]]
==== Using GUI

.Procedure: Set Home Routing Charge using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Diameter' tab in the GUI. 
. You can set 'Home Routed SMS Charged' value to none, selected or all, in the corresponding list.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_dest_txhttpcharging]]
=== HTTP Charge Settings

[[_dest_txhttpcharging_cli]]
==== Using CLI

You can set the 'HTTP Originated SMS Charged' value by issuing the command `smsc set txhttpcharging` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get txhttpcharging` which will display the value set for this property. 

----

Name
	smsc set txhttpcharging

SYNOPSIS
	smsc set txhttpcharging <accept|reject|diameter>

DESCRIPTION
	This command is used to set the value of the parameter 'txHttpCharging' to
	needed values (accepting of messages that come from a HTTP connector).
	This value is set to accept by default.

	If this is set to 
	accept - all incoming messages are accepted without charging
	reject - all incoming messages will be rejected
	diameter - all incoming messages are checked by Diameter peer before delivering
	(this option is not supported now)

EXAMPLES
	smsc set txhttpcharging accept
----

[[_dest_txhttpcharging_gui]]
==== Using GUI

.Procedure: Set HTTP originated Charge using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Diameter' tab in the GUI. 
. You can set 'HTTP originated SMS Charged' value to accept, reject or diameter, in the corresponding list.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 




[[_smsc_gateway_server_hr]]
== Home Routing Settings

{this-platform} SMSC Gateway supports Non Transparent Home Routing as explained in 3GPP 23.840 5.2.3.
This option can be disabled by setting "hrcharging" option to "reject" (see <<_dest_hrcharging>>). SMSC GW will accept SendRoutinInfo requests from a remote SMSC, then create a unique "correlationId" value for a requested MSISDN, then send SendRoutinInfo request to HLR, store received by HLR info into a cache and sends back to the remote SMSC SendRoutinInfo response with "correlationId" value in IMSI field and SMSC GlobalTytle (or another special configured GlobalTytle value) in LocationInfo field.
Then SMSC GW will accept MtForwardSM messages from the remote SMSC, seaches in the cache for "correlationId" and HLR subscriber's and use this data for processing a message further. 

[[_smsc_gateway_server_hr_corrtable]]
=== Correlation table CC and MCC-MNC for home routing mode managing.

For home routing mode we may need to fill a special table for correlation between CC (CountryCodes) of incoming MSISDN address and MCC-MNC prefix of a generated correlationId value.
CorrelationId value will be returned as IMSI in SRI response to an upper SMSC GW.
As an extra field "smsc" field can be specified for each entry of this table.
If this field is specified and not empty then this value will be returned as a LocationInfo in SRI response to an upper SMSC GW, else SMSC GW address will be returned.
Correlation table is stored into "jboss-5.1.0.GA/server/<server instanse, for example 'default'>"/data" and has name "SmscManagement_cc_mccmnc.xml". The content of this should follow the following template: 


----

<?xml version="1.0" encoding="UTF-8" ?>
  <CcMccmncCollection>
  <ccMccmncList>
    <ccMccmnc countryCode="0111" mccMnc="77702"/>
    <ccMccmnc countryCode="0222" mccMnc="9999999"/>
    <ccMccmnc countryCode="02" mccMnc="8888888" smsc="06060606"/>
    <ccMccmnc countryCode="" mccMnc="22323"/>
  </ccMccmncList>
</CcMccmncCollection>
----


The file structure consists on one or several instances of countryCode / mccMnc pairs.
When SMSC GW reads a correlation table from the file (or when a user add new entries into the table) it sorts it so that the longer CountryCode values (more detailed "CountryCode") are put at first places of the list then shorter CountryCode values.
For example "44779" will be before "44". First found "mccMnc" value will be used for correlationId generating.
When SMSC GW receives a SRI request from an upper SMSC GW it looks throught  the table, checks if incoming MSISDN digits start from countryCode value from a table entry.
The last entry in the correlation table must be empty ("") countryCode value.
This entry will be used as a default value.
All MSISDN that are not fit to any other entries will use mccMnc of the entry of "". You can also add an optional extra field "smsc" into any record.
This value will be used as LocationInfo field in SendRoutinInfo response. 

[[_correlationidlivetime]]
=== Living time of elements in correlation cache

[[_correlationidlivetime_cli]]
==== Using CLI

In home routing mode SMSC GW specifies correlationId for any recieved SRI requests from upper SMSC.
After it this correlationId value and corresponded to MSISDN data are stored into internal cache and will be used for processing of next coming MtForwardSM messages from other SMSC.
Correlationidlivetime value defines how much time minimum is correlationId in cache.
You can set the 'correlationidlivetime' option by issuing the command ``smsc set correlationidlivetime`` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get correlationidlivetime` which will display the value set for this property. 

Also pay attention that when Telestax SMSC delivers messages received under "home routing" procedure SMSC GW will try to reuse location info and IMSI data that SMSC GW has obtained when request to HLR under "home routing" procedure.
SMSC GW will try to reuse this info only till it is kept in correlationId cache.
When ForwardAndStore and datagram modes this is usually achived in correlationidlivetime is 60 seconds.
In StoreAndForward mode messages delivery can be started some time after messages have come to SMSC GW.
This delay depends on both SMSC GW setting (first delivery attempt) and SMSC GW overloadload rate.
For StoreAndForward mode we need to caluclate a proper correlationidlivetime value depending on othe SMSC setting.
But do not make this value too big - this will waste memory and location info can occure too old. 

----

Name
    smsc set correlationidlivetime

SYNOPSIS
    smsc set correlationidlivetime <digital option>

DESCRIPTION
    This command is used to set min time duration for which 
    correlationId and corresponded data kept in cache. Max
    duratuion is two times more then correlationidlivetime.
    Value is in seconds.

    Default value: 60 (seconds).

EXAMPLES
    smsc set correlationidlivetime 90
----

[[_correlationidlivetime_gui]]
==== Using GUI

.Procedure: Setting of living time of elements in correlation cache using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Home Routing' tab in the GUI. 
. You can specify CDR generation option by selecting an appropriate value in the field "Correlation Id Cache Time (in secs)". For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_hrsribypass]]
=== Bypassing of SRI request to a local HLR

[[_hrsribypass_cli]]
==== Using CLI

SMSC GW home routing procedure for each networkId area can be configured to send or do not send SendRoutinInfo request to a local HLR.
This is configured by parameter "hrsribypass". Default value is "false" - this means that SMSC GW will send SRI requests to local HLR before sending back SRI response. 

.Messageflow for home routing procedure when hrsribypass==false
::
  SRI request:  remote SMSC GW -> Telscale SMSC GW

::
  SRI request:  Telscale SMSC GW -> local HLR

::
  SRI response: local HLR -> Telscale SMSC GW

::
  SRI response: Telscale SMSC GW -> remote SMSC GW

::
  MT request:   remote SMSC GW -> Telscale SMSC GW

::
  MT response:  Telscale SMSC GW -> remote SMSC GW	

.Messageflow for home routing procedure when hrsribypass==true (SRI request to local HLR bypassing)
::
  SRI request:  remote SMSC GW -> Telscale SMSC GW

::
  SRI response: Telscale SMSC GW -> remote SMSC GW

::
  MT request:   remote SMSC GW -> Telscale SMSC GW

::
  MT response:  Telscale SMSC GW -> remote SMSC GW
You can set the 'hrsribypass' option by issuing the command ``smsc set hrsribypass`` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get hrsribypass` which will display the value set for this property. 

----

Name
    smsc set hrsribypass

SYNOPSIS
    smsc set hrsribypass <digital option> networkid <networkId>

DESCRIPTION
    This command is used to set if SMSC GW will
    bypass a SRI to a local HLR.

	networkId - specifies a virtual SS7 subnetwork (this is for Multi-tenancy
	support). By using of this command with different networkIds you can
	specify hrsribypass for several subnetworks. 
	If this parameter is skipped - networkId will be set to "0".
	If you have not specified hrsribypass parameter for a networkId
	then a master hrsribypass will be used (that was specified for
	networkId 0).

    Default value: false.

EXAMPLES
    smsc set hrsribypass true
    smsc set hrsribypass false networkid 2
----

[[_hrsribypass_gui]]
==== Using GUI

.Procedure: Setting of living time of elements in correlation cache using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Home Routing' tab in the GUI. 
. You can specify hrsribypass option by selecting an appropriate value in the field "Bypassing of SRI request to a local HLR" for a specified networkId. Select needed "Bypassing of SRI request to a local HLR Network Id" field value or type a new networkId value if no such value already specifyied. Then select needed value into below field ("Removing value from networkId" means just remove "Bypassing of SRI request" for a selected networkId).
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section. 
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_hrccmccmnc_add]]
=== Create an entry for correlation table CC and MCC-MNC

[[_hrccmccmnc_add_cli]]
==== Using CLI

In home routing mode SMSC GW we may need to specify the correlation table CC and MCC-MNC (<<_smsc_gateway_server_hr_corrtable>>). You can add an entry of this table by issuing the command ``smsc hrccmccmnc add`` with appropriate parameters as described below. 

----

Name
    smsc hrccmccmnc add

SYNOPSIS
    smsc hrccmccmnc add <countrycode> <mccmnc> smscgt <smsc-gt>

DESCRIPTION
    This command is used to add an entry to the correlation
    table CC and MCC-MNC.
    mscgt parameter is optional. If it is missed will be set]
    to "null" value. For "null" value for <smsc-gt> we can
    to specify "-1" value in CLI.

EXAMPLES
    smsc hrccmccmnc add 2223 55322 smscgt 733211232342
----

[[_hrccmccmnc_add_gui]]
==== Using GUI

.Procedure: Creation an entry for correlation table CC and MCC-MNC using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Home Routing CC - MCC MNC Table' in the left panel. 
. You can add an entry of the table - you can specify "Country Code", "Mobile Country Code and Mobile Network Code", "Global Title" (optionally) and press "Add" button.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.

[[_hrccmccmnc_modify]]
=== Modification of an entry for correlation table CC and MCC-MNC

[[_hrccmccmnc_modify_cli]]
==== Using CLI

In home routing mode SMSC GW we may need to specify the correlation table CC and MCC-MNC (<<_smsc_gateway_server_hr_corrtable>>). You can modify an entry of this table by issuing the command ``smsc hrccmccmnc modify`` with appropriate parameters as described below. 

----

Name
    smsc hrccmccmnc modify

SYNOPSIS
    smsc hrccmccmnc modify <countrycode> <mccmnc> smscgt <smsc-gt>

DESCRIPTION
    This command is used to modify an entry to the correlation
    table CC and MCC-MNC.
    mscgt parameter is optional. If this parameter is missed mscgt
    value will not updated. To set "null" value for <smsc-gt> we
    need to specify "-1" value in CLI.

EXAMPLES
    smsc hrccmccmnc modify 2223 55322 smscgt 733211232342
----

[[_hrccmccmnc_modify_gui]]
==== Using GUI

.Procedure: Modification of an entry for correlation table CC and MCC-MNC using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Home Routing CC - MCC MNC Table' in the left panel. 
. You can modify an entry of the table - you can specify "Country Code", "Mobile Country Code and Mobile Network Code", "Global Title" (optionally) and press "Update" button.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.

[[_hrccmccmnc_remove]]
=== Removing of an entry for correlation table CC and MCC-MNC

[[_hrccmccmnc_remove_cli]]
==== Using CLI

In home routing mode SMSC GW we may need to specify the correlation table CC and MCC-MNC (<<_smsc_gateway_server_hr_corrtable>>). You can remove an entry of this table by issuing the command ``smsc hrccmccmnc remove`` with appropriate parameters as described below. 

----

Name
    smsc hrccmccmnc remove

SYNOPSIS
    smsc hrccmccmnc remove <countrycode>

DESCRIPTION
    This command is used to remove an entry to the correlation
    table CC and MCC-MNC.

EXAMPLES
    smsc hrccmccmnc remove 2223
----

[[_hrccmccmnc_remove_gui]]
==== Using GUI

.Procedure: Removing of an entry for correlation table CC and MCC-MNC using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Home Routing CC - MCC MNC Table' in the left panel. 
. You can delete an entry of the table you - can specify "Country Code" and press "Delete" button.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.

[[_hrccmccmnc_show]]
=== Displaying of an entry / full list of correlation table CC and MCC-MNC

[[_hrccmccmnc_show_cli]]
==== Using CLI

In home routing mode SMSC GW we may need to specify the correlation table CC and MCC-MNC (<<_smsc_gateway_server_hr_corrtable>>). You can observe an entry or a full list of this table by issuing the command ``smsc hrccmccmnc show`` with appropriate parameters as described below. 

----

Name
    smsc hrccmccmnc show

SYNOPSIS
    smsc hrccmccmnc show <countrycode>

DESCRIPTION
    This command is used to display of content of an entry
    or a full list of the correlation table CC and MCC-MNC.
    <countrycode> is an optional parameter. If you specify
    it data for only this entry will be displayed. If not
    - data for all entries of that table.

EXAMPLES
    smsc hrccmccmnc show 2223
----

[[_hrccmccmnc_show_gui]]
==== Using GUI

.Procedure: Displaying of an entry for correlation table CC and MCC-MNC using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Home Routing CC - MCC MNC Table' in the left panel. 
. You can view content of an entry of the table you or of all table.
  For viewing of one entry you need to specify "Country Code". Then press "View" button.
  Results will be shown in the bottom of the screen For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.

[[_smsc_gateway_server_cdr]]
== CDRs and archive tables

[[_generatecdr]]
=== CDR generation

[[_generatecdr_cli]]
==== Using CLI

SMSC GW can store CDR records for each delivered or failed for delivering messages into log file (see <<_cdr_logging_settings>>). Which records will be stored is defined by 'generatecdr' SMSC option.
You can set the 'generatecdr' option by issuing the command ``smsc set generatecdr`` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get generatecdr` which will display the value set for this property. 

----
Name
	smsc set generatecdr

SYNOPSIS
	smsc set generatecdr <0 | 1 | 2 | 4 | 7>

DESCRIPTION
	This command is used to set the generatecdr value. generatecdr
	defines which messages records will be added into .txt CDR's
	
	Options will have following bits values:
	
	1 - records will be done for SMPP originated messages with 
	datagramm mode
	2 - records will be done for SMPP originated messages with 
	transactional mode
	4 - records will be done for SMPP originated messages with 
	storeAndForward mode and for all SS7 or SIP originated messages
	
	Value 0 will mean store none and value 7 - store all.
	Default value: 7

EXAMPLES
	smsc set generatecdr 7
----

[[_generatecdr_gui]]
==== Using GUI

.Procedure: Set CDRs generation SMSC option using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'CDR' tab in the GUI. 
. You can specify CDR generation option by selecting an appropriate value in the field "CDR generation". For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_generatearchivetable]]
=== Archive table generation

[[_generatearchivetable_cli]]
==== Using CLI

SMSC GW can store CDR records for each delivered or failed for delivering messages into special archive tables of cassandra database.
Names of such tables have the following format: MESSAGES_yyyy_mm_dd.
You can refer to fields definitions in <<_messages_yyyy_mm_dd>> chapter.
Which records will be stored is defined by 'generatearchivetable' SMSC option.
You can set the 'generatearchivetable' option by issuing the command `smsc set generatearchivetable` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get generatearchivetable` which will display the value set for this property. 

----

Name
    smsc set generatearchivetable

SYNOPSIS
    smsc set generatearchivetable <digital option>

DESCRIPTION
    This command is used to set which messages (or none) will be stored into
    archive tables. Options will have following bits values:
    bit 1 - records will be done for SMPP originated messages with datagramm
            mode
    bit 2 - records will be done for SMPP originated messages with
            transactional mode
    bit 4 - records will be done for SMPP originated messages with
            storeAndForward mode and for all SS7 or SIP originated messages
    Value 0 will mean store none and value 7 - store all.
    Default value: 7 (store all)
EXAMPLES
    smsc set generatearchivetable 7
----

[[_generatearchivetable_gui]]
==== Using GUI

.Procedure: Set archive table CDRs generation SMSC option using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'CDR' tab in the GUI. 
. You can specify archive table CDR generation option by selecting an appropriate value in the field "Archive table generation". For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 


[[_generatereceiptcdr]]
=== Generate CDR for Receipt Messages

[[_generatereceiptcdr_cli]]
==== Using CLI

You can set the 'generatereceiptcdr' value to true/false by issuing the command `smsc set generatereceiptcdr` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get generatereceiptcdr` which will display the value set for this property. 

----
Name
	smsc set generatereceiptcdr

SYNOPSIS
	smsc set generatereceiptcdr <true | false>

DESCRIPTION
	The SMSC can be configured to generate CDR for both receipt and regular messages 
	or generate CDR only for regular messages. By default the SMSC will generate CDR
	for regular messages only. However if you require the SMSC to generate CDR for
	receipt messages as well, you must set the parameter 'generatereceiptcdr' to true.
	Default value: false

EXAMPLES
	smsc set generatereceiptcdr false
----

[[_generatereceiptcdr_gui]]
==== Using GUI

.Procedure: Set 'generate CDR for receipt messages'  using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'CDR' tab in the GUI. 
. You can specify if the SMSC should generate CDR for receipt messages by choosing the value true for the field 'Generate receipt CDR'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 


[[_generatetempfailurecdr]]
=== Generate CDR for temporary failure case

[[_generatetempfailurecdr_cli]]
==== Using CLI

You can set the 'generatetempfailurecdr' value to true/false by issuing the command `smsc set generatetempfailurecdr` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get generatetempfailurecdr` which will display the value set for this property. 

----
Name
	smsc set generatetempfailurecdr

SYNOPSIS
	smsc set generatetempfailurecdr <true | false>

DESCRIPTION
	The SMSC can be configured to generate CDR for a successful delivery case,
	a permanent failure case and a temporary failure case. If we configure
	generatetempfailurecdr to true then CDR will be generated for all cases.
	If we configure generatetempfailurecdr to false then CDR will be generated for
	successful delivery and permanent failure cases and not for a temporary failure
	case.
	Default value: true

EXAMPLES
	smsc set generatetempfailurecdr true
----

[[_generatetempfailurecdr_gui]]
==== Using GUI

.Procedure: Set 'generate CDR for a temporary failure case'  using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'CDR' tab in the GUI. 
. You can specify if the SMSC should generate CDR for for a temporary failure case by choosing the value true for the field 'Generate CDR for a temporary failure case'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 


[[_generateprocessingerrorcdr]]
=== Generate CDR for Message Processing Errors

[[_generateprocessingerrorcdr_cli]]
==== Using CLI

You can set the 'generateprocessingerrorcdr' value to true/false by issuing the command `smsc set generateprocessingerrorcdr` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get generateprocessingerrorcdr` which will display the value set for this property. 

----
Name
  smsc set generateprocessingerrorcdr

SYNOPSIS
  smsc set generateprocessingerrorcdr <true | false>

DESCRIPTION
  The SMSC can be configured to generate CDR also for unsuccessful message
  processing. This applies both to a variety of SMSC errors (unexpected
  internal and/or external) as well as to intentional message rejection by
  MProc rules.
  Default value: false

EXAMPLES
  smsc set generateprocessingerrorcdr false
----

[[_generateprocessingerrorcdr_gui]]
==== Using GUI

.Procedure: Set 'generate CDR for message processing error'  using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'CDR' tab in the GUI. 
. You can specify if the SMSC should generate CDR for message processing errors by choosing the value true for the field 'Generate CDR for an SMSC processing error case'. For more details of this parameter, please refer to the description of the CLI command in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 


[[_calculatemsgpartslencdr]]
=== Calculating of message parts and characters count per a CDR record

[[_calculatemsgpartslencdr_cli]]
==== Using CLI

You can set the 'calculatemsgpartslencdr' value to true/false by issuing the command `smsc set calculatemsgpartslencdr` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get calculatemsgpartslencdr` which will display the value set for this property. 

----
Name
	smsc set calculatemsgpartslencdr

SYNOPSIS
	smsc set calculatemsgpartslencdr <true | false>

DESCRIPTION
	When SMSC GW generates CDR records it can calculate message parts and characters
	count per a CDR record. Message parts count means a count of parts to that
	SMSC GW will have to split a long messages when sending messages into SS7 network.
	This demands some extra calculating and therefore is disabled by default.
	You can turn it on by setting to a true of calculatemsgpartslencdr option.
	Default value: false

EXAMPLES
	smsc set calculatemsgpartslencdr false
----

[[_calculatemsgpartslencdr_gui]]
==== Using GUI

.Procedure: Set 'calculating of message parts and characters count per a CDR record'  using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'CDR' tab in the GUI. 
. You can specify if the SMSC should calculating of message parts and characters count per a CDR record by choosing the value true for the field 'Calculating of message parts and characters count per a CDR record'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 


[[_delayparametersincdr]]
=== Adding of delay parameters into a CDR record

[[_delayparametersincdr_cli]]
==== Using CLI

You can set the 'delayparametersincdr' value to true/false by issuing the command `smsc set delayparametersincdr` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get delayparametersincdr` which will display the value set for this property.

----
Name
	smsc set delayparametersincdr

SYNOPSIS
	smsc set delayparametersincdr <true | false>

DESCRIPTION
	When SMSC GW generates CDR records it can calculate a message processing time,
	delivery delay, schedule delivery delay and delivery count per a CDR record.
	This demands some extra calculating and therefore is disabled by default.
	You can turn it on by this option.
	Default value: false

EXAMPLES
	smsc set delayparametersincdr true
----

[[_delayparametersincdr_gui]]
==== Using GUI

.Procedure: Set 'Adding of delay parameters into a CDR record'  using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel.
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'CDR' tab in the GUI.
. You can specify if the SMSC should add of delay parameters into a CDR record by choosing the value true for the field 'Delay parameters in CDR'. For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below.






[[_smsc_gateway_server_processing]]
== Processing

[[_modefaultmessagingmode]]
=== Messaging mode for MO messages

[[_modefaultmessagingmode_cli]]
==== Using CLI

You can set the messaging mode for MO originated messages value by issuing the command `smsc set modefaultmessagingmode` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get modefaultmessagingmode` which will display the value set for this property. 

----

Name
	smsc set modefaultmessagingmode

SYNOPSIS
	smsc set modefaultmessagingmode <messaging mode value>

DESCRIPTION
	This command is used to set a value for default messaging mode
	value for mobile originated (MO) messages.
	Possible values: 0-default SMSC mode, 1-datagram, 2-transactional,
	3-storeAndForward.
	Default value is 3.

EXAMPLES
	smsc set modefaultmessagingmode 3
----

[[_modefaultmessagingmode_gui]]
==== Using GUI

.Procedure: Set the messaging mode for MO originated messages option using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel.
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Processing' tab in the GUI.
. You can specify the messaging mode for MO originated messages option by selecting an appropriate value in the field "Default messaging mode - MO messages". For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_hrdefaultmessagingmode]]
=== Messaging mode for HR messages

[[_hrdefaultmessagingmode_cli]]
==== Using CLI

You can set the messaging mode for HR originated messages value by issuing the command `smsc set hrdefaultmessagingmode` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get hrdefaultmessagingmode` which will display the value set for this property. 

----

Name
	smsc set hrdefaultmessagingmode

SYNOPSIS
	smsc set hrdefaultmessagingmode <messaging mode value>

DESCRIPTION
	This command is used to set a value for default messaging mode
	value for messages that came by SS7 Home Routing procedure.
	Possible values: 0-default SMSC mode, 1-datagram, 2-transactional
	(this means HR transparent mode), 3-storeAndForward.
	Default value is 3.

EXAMPLES
	smsc set hrdefaultmessagingmode 3
----

[[_hrdefaultmessagingmode_gui]]
==== Using GUI

.Procedure: Set the messaging mode for HR originated messages option using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel.
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Processing' tab in the GUI.
. You can specify the messaging mode for HR originated messages option by selecting an appropriate value in the field "Default messaging mode - HR messages". For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

[[_sipdefaultmessagingmode]]
=== Messaging mode for SIP messages

[[_sipdefaultmessagingmode_cli]]
==== Using CLI

You can set the messaging mode for SIP originated messages value by issuing the command `smsc set sipdefaultmessagingmode` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get sipdefaultmessagingmode` which will display the value set for this property. 

----

Name
	smsc set sipdefaultmessagingmode

SYNOPSIS
	smsc set sipdefaultmessagingmode <messaging mode value>

DESCRIPTION
	This command is used to set a value for default messaging mode
	value for messages from a SIP connector.
	Possible values: 0-default SMSC mode, 1-datagram, 2-transactional,
	3-storeAndForward. Transactional mode mode is not supported now.
	Default value is 3.

EXAMPLES
	smsc set sipdefaultmessagingmode 1
----

[[_sipdefaultmessagingmode_gui]]
==== Using GUI

.Procedure: Set the messaging mode for SIP originated messages option using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel.
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Processing' tab in the GUI.
. You can specify the messaging mode for SIP originated messages option by selecting an appropriate value in the field "Default messaging mode - SIP messages". For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 

=== SMSC pausing

[[_smsc_pausing_cli]]
==== Using CLI

A user can pause SMSC for message delivering by issuing the command `smsc set deliverypause` with appropriate parameters as described below.
When SMSC delivery is paused no more messages are scheduled for delivering.
When SMSC is configured in ForwardAndStore (fast) mode all incoming messages will be rejected.
When SMSC is configured in StoreAndForward (normal) mode datagramm and transactional SMPP originated messages will be rejected but StoreAndForward SMPP originated and all SS7 / SIP originated messages will be stored into cassandra database without delivery attempts.
Use this option with extreme caution. 

----

	Name
	    smsc set deliverypause
	
	SYNOPSIS
	    smsc set deliverypause <true|false>
	
	DESCRIPTION
	    Setting to true puts SMSC GW into a pause mode and setting to false
	    (default value) returns SMSC GW to a normal message processing.
	EXAMPLES
	    smsc set deliverypause true
----

[[_smsc_pausing_gui]]
==== Using GUI

.Procedure: Pause SMSC using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. You can select "true" or "false" value.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Apply Changes' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below.

[[_receiptsdisabling]]
=== Disabling of Reciepts generating

[[_receiptsdisabling_cli]]
==== Using CLI

SMCS can generate receipts of messages delivering results (success / error). See chapter "Appendix B.
Delivery Receipt Format" of "Short Message Peer to Peer.
Protocol Specification v3.4." You can set the 'receiptsdisabling' value to true/false by issuing the command `smsc set receiptsdisabling` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get receiptsdisabling` which will display the value set for this property. 

----

Name
    smsc set receiptsdisabling

SYNOPSIS
    smsc set receiptsdisabling <true | false>

DESCRIPTION
    The SMSC can be configured to generat or not delivery receipts.
     Setting of receiptsdisabling to false enables of receipts generation.
     Setting of receiptsdisabling to true disables of receipts generation.
     Default value: false (receipts will be generated).
----

[[_receiptsdisabling_gui]]
==== Using GUI

.Procedure: Disabling of Reciepts generating using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Processing' tab in the GUI. 
. You can specify if the SMSC should disable of receipt generating by setting the value for the field 'Disable Delivery Receipt' to true or false accordingly.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 


[[_enableintermediatereceipts]]
=== Allowing of generating of intermediate receipts

[[_enableintermediatereceipts_cli]]
==== Using CLI

SMCS can generate intermediate receipts (for temporary failures). You can set the 'enableintermediatereceipts' value to true/false by issuing the command `smsc set enableintermediatereceipts` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get enableintermediatereceipts` which will display the value set for this property. 

----

Name
    smsc set enableintermediatereceipts

SYNOPSIS
    smsc set enableintermediatereceipts <true | false>

DESCRIPTION
    The SMSC can be configured to generate or not delivery intermediate receipts
	(these are receipts for temporary delivery failures).
	Default value: false (intermediate receipts will not be generated).

----


[[_incomereceiptsprocessing]]
=== Income receipts processing

[[_incomereceiptsprocessing_cli]]
==== Using CLI

SMCS can processing of incoming delivery receipts from remote SMSC GW (replacing of messageId in the receipt by a local messageId). You can set the 'incomereceiptsprocessing' value to true/false by issuing the command `smsc set incomereceiptsprocessing` with appropriate parameters as described below.
You can verify this by issuing the command `smsc get incomereceiptsprocessing` which will display the value set for this property. 

----

Name
    smsc set incomereceiptsprocessing

SYNOPSIS
    smsc set incomereceiptsprocessing <true | false>

DESCRIPTION
	Enabling of processing of incoming delivery receipts from remote SMSC GW.
	When a delivery receipt comes from a remote SMSC GW, then
	SMSC GW will replace messageId in the receipt by a local messageId.
	This action is needed for a possibility of delivery receipts processing
	in mproc rules staff and delivery receipts transit to message originators.
	Default value: false (no remote delivery receipts processing).

----


[[_incomereceiptsprocessing_gui]]
==== Using GUI

.Procedure: Allowing of generating of intermediate receipts using the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Processing' tab in the GUI. 
. You can specify of processing of incoming delivery receipts by setting the value for the field 'Income receipts processing' to true or false accordingly.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 


[[_smsc_gateway_server_routing_dlv]]
=== Routing of delivery receipts

[[_smsc_gateway_server_routing_dlv_cli]]
==== Using CLI

If this option is turned on for each generated delivery receipts and SMS-STATUS-REPORTs networkId will be assigned to the value of networkId of an ESME via which the original message has come to SMSC.
This can help for routing of receipts back to the originated ESME.
If this option is turned off then the networkId of receipts will be taken from networkId of ESME / SS7 / SIP via which the original message has left SMSC GW.
You can configure this option by issuing the command smsc set orignetworkidforreceipts with appropriate parameters as described below. 

----

Name
    smsc set orignetworkidforreceipts

SYNOPSIS
    smsc set orignetworkidforreceipts <true | false>

DESCRIPTION

	Settings of this option will affect of which networkId will be assigned
	to a message delivery receipt.
	true: networkId of the connector via which an original message has 
	      left SMSC GW
	false: networkId of the connector via which an original message has
	       come SMSC GW. This value is default.
----

[[_smsc_gateway_server_routing_dlv_gui]]
==== Using GUI

.Procedure: Routing of delivery receipts option update by the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel. 
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Processing' tab in the GUI. 
. You can specify routing of delivery receipts by setting the value for the field 'Delivery receipts will be routed to the origination networkId' to true or false accordingly.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 


[[_smsc_gateway_min_messageid]]
=== Minimum MessageId value

[[_smsc_gateway_min_messageid_cli]]
==== Using CLI

You can set the 'Minimum MessageId value' value by issuing the command ``smsc set minmessageid`` with appropriate parameters as described below.
You can verify this by issuing the command ``smsc get minmessageid`` which will display the value set for this property.
----

Name
	smsc set minmessageid

SYNOPSIS
	smsc set minmessageid <min-MessageId-value>

DESCRIPTION
	This command is used to set the value of minimum MessageId value
	that is put into SMPP submit_sm_response.
	Default value is 1.
	You need to restart SMSC GW in order to changing will make effect.
----

[[_smsc_gateway_max_messageid_gui]]
==== Using GUI

.Procedure: Minimum MessageId value option update by the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel.
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Processing' tab in the GUI. 
. You can specify routing of delivery receipts by setting the value for the field 'Minimum MessageId value' to a neede value.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 


[[_smsc_gateway_max_messageid]]
=== Maximum MessageId value

[[_smsc_gateway_max_messageid_cli]]
==== Using CLI

You can set the 'Maximum MessageId value' value by issuing the command ``smsc set maxmessageid`` with appropriate parameters as described below.
You can verify this by issuing the command ``smsc get maxmessageid`` which will display the value set for this property.
----

Name
	smsc set maxmessageid

SYNOPSIS
	smsc set maxmessageid <max-MessageId-value>

DESCRIPTION
	This command is used to set the value of maximum MessageId value
	that is put into SMPP submit_sm_response.
	Default value is 10000000000L.
	You need to restart SMSC GW in order to changing will make effect.
----

[[_smsc_gateway_max_messageid_gui]]
==== Using GUI

.Procedure: Maximum MessageId value option update by the GUI
. In the GUI Management Console for SMSC Gateway, click on 'Server Settings' in the left panel.
. The main panel will display the existing Settings, segregated into eight horizontal tabs: Properties, SS7 Settings, Cassandra, Scheduler, Diameter, Processing, CDR and Home Routing.
  Switch to the 'Processing' tab in the GUI. 
. You can specify routing of delivery receipts by setting the value for the field 'Maximum MessageId value' to a neede value.
  For more details of this parameter, please refer to the description of the CLI command for the same in the preceding section.
. You must click on the button 'Save' at the top of the window to save your settings.
  If there is an error in setting the value, then you will find the details of the error in the Management Console Log section below. 
  
