= Introduction

{this-platform} {this-application} is an Open Source Java based SMSC Gateway built on a modern extensible middleware platform. {this-platform} SMSC enables operators to provide core SMSC features like mobile subscriber to subscriber SMS messaging, broadcasting campaigns and group messagingfootnote:[Group Messaging can be achieved using  RestComm. For more details please contact info@telestax.com.] between subscribers.
In addition it also enables value added services through integration with OTT social networks and microblogs such as Facebook and Twitter.
 

{this-platform} {this-application} is an easy-to-install and easy-to-deploy platform that can be set up and configured very quickly.
Since it is built on a modern and extensible JSLEE platform it automatically provides out-of-the-box integration with various communication protocols such as SIP, Diameter, HTTP, XCAP, XMPP, MGCP and others in addition to the base SMPP protocol for connectivity to ESMEs.
 

{this-platform} {this-application} stores messages using Cassandra database.
The database is used for storing unsent messages, messages successfully sent and messages that failed to be sent. 

{this-platform} {this-application} is cloud-ready.
It can be deployed on dedicated hardware, private cloud infrastructure or public laaS such as AWS. {this-platform} {this-application} supports TDM hardware offered by major vendors in the market, namely Intel family boards (Dialogic) and  Zaptel/Dahdi (Digium, Sangoma).
 

A single {this-platform} SMSC node can process up to 1000 SMS/sec.
Multiple SMSC nodes can be arranged in a cluster across one or more geographically distributed data centers to scale up throughput and provide various levels of redundancy, high availability and fault tolerance. 

{this-platform} {this-application} is based on the robust and proven {this-platform} JAIN SLEE 1.1 Server and {this-platform} jSS7 Stack. {this-platform} JAIN SLEE Server is a highly scalable event-driven application server with a robust component model and fault tolerant execution environment.
It provides a set of connectors to a variety of networks elements: SS7 MAP, CAP, INAP, TCAP, ISUP, SMPP, XMPP, SIP, MGCP, HTTP, XDM, XCAP, Diameter and many others.
It is fully compliant with JSR 240 (JSLEE 1.1). {this-platform} jSS7 is a software based implementation of the SS7 protocol.
It provides implementation for Level 2 and above in the SS7 protocol Stack. {this-platform} jSS7 Stack User Guide is bundled within and you can refer to the guide for more details on the Stack. 

This guide will assist you in installing {this-platform} {this-application} .
For more details on configuring and using the platform, please refer to the {this-platform} {this-application} Admin Guide.
 
