[[_setup_database]]
= Database Setup

{this-platform} {this-application} stores messages using Cassandra database.
The database is used for storing unsent messages, messages successfully sent and messages that failed to be sent.
You must have Cassandra database (versions 2.1 or 3.*) installed. Later versions are better. Vesrions 1.2 and 2.0 are not supported more.

NOTE: Cassandra database version 3.0 demands JAVA 8 but {this-platform} {this-application} {project-version} based on jboss 5.1 server supports only JAVA 7. You can use {this-platform} {this-application} based on Wildfly 10 server that supports JAVA 8. If you have both cassandra database and {this-platform} {this-application} based on jboss 5.1 installed at the same host then you need to install two JAVA versions and switch between them by usage of JAVA_HOME environmental variables.

NOTE: {this-platform} {this-application} uses Cassandra Native Driver and therefore you should enable support for native drivers by setting the value of `start_native_transport` to `true` in the file [path]_apache-cassandra-<version>/conf/cassandra.yaml_.
Failure to do this may result in the Gateway not starting correctly.

To install the Cassandra database, look for distributives at the offical Apache website here http://cassandra.apache.org/download/.
We recommend that you download the latest binaries and install the database following the instructions specified in the Apache documentation in their website http://wiki.apache.org/cassandra/GettingStarted. 

If you already use old cassandra database version, you must think to update it to a newer version when it is possible before next version has been released.
If you do not have database routing rules and it is not important to you to lose of pending messages in SMSC GW, you can just remove RestCommSMSC Keyspace, uninstall old version, install a new one and create an empty RestCommSMSC Keyspace.
Else you can update your database as DataStax recommends: http://docs.datastax.com/en/latest-upgrade/upgrade/cassandra/upgrdCassandraDetails.html. 

{this-platform} {this-application} use 2 types of keyspaces:

* a dedicated KeySpace (default name is "RestCommSMSC") used for storing of messages and configs for concrete SMSC GW instance (we have a KeySpace per a SMSC GW instance), it is mandatory if we want to use stroreAndForward mode.
* a shared KeySpace (default name is "Shared") used for exchange of information between SMSC GW instances in cluster (we have a KeySpace for all SMSC GW cluster). Find more info in a User Guide chapter "Configuring of SS7 Active-Active mode with
Telscale SS7 FEP before SS7 network". This KeySpace is needed only for a cluster work.  

Before a first {this-platform} {this-application} start we need to create an empty dedicated keyspace per SMSC GW instance (and one empty shared KeySpace only in clustering mode). {this-application} creates all needed tables itself after starting of {this-application}.  
